const escape = value => String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function token(){try{return JSON.parse(localStorage.getItem('level_up_cloud_session')||'{}').token||'';}catch{return '';}}
async function api(path='',method='GET',body){const t=token(),r=await fetch('https://api.leveluphypertrophy.com/v1/features'+path,{method,headers:{'Content-Type':'application/json',...(t?{Authorization:'Bearer '+t}:{})},body:body?JSON.stringify(body):undefined});const data=await r.json();if(!r.ok)throw Error(data.error||'Please try again.');return data;}
export async function openFeatureBoard(){
 if(!document.getElementById('feature-board-styles')){const style=document.createElement('link');style.id='feature-board-styles';style.rel='stylesheet';style.href=new URL('../../css/feature-board.css?v=owner-feature-review-1',import.meta.url).href;document.head.append(style);}
 const root=document.getElementById('content');root.innerHTML=`<section class="dashboard-welcome"><div><button id="feature-back" class="nutrition-planner-back">← More</button><span class="eyebrow">HELP & SUPPORT</span><h2>Request a Feature</h2><p>Help shape Level Up. Suggest a feature or vote for an idea you’d like us to build.</p></div></section><section class="support-report-card"><label for="feature-search">Search requests</label><input id="feature-search" type="search" placeholder="Search before suggesting an idea"><div id="feature-filters" class="feature-board-filters" role="group" aria-label="Feature requests"></div><p id="feature-visibility"></p><div id="feature-list"></div><button id="feature-more" type="button" hidden>Load more requests</button><div id="feature-detail"></div></section><section class="support-report-card"><h3>Suggest a feature</h3>${token()?`<form id="feature-new" class="support-report-form"><label for="feature-title">Feature title</label><input id="feature-title" maxlength="120" required><label for="feature-body">What would you like to do, and how would it help?</label><textarea id="feature-body" maxlength="3000" required></textarea><p>Requests appear publicly after review. Only your first name is shown. Votes help us prioritize; they do not guarantee a feature will be built.</p><button class="support-send-btn">Submit request</button></form>`:'<p>Sign in under More → Account & Cloud to submit requests, vote or comment.</p>'}<p id="feature-message" role="status"></p></section>`;
 root.querySelector('#feature-back').onclick=()=>document.querySelector('.nav-btn[data-page="more"]')?.click();
 let requests=[],admin=false,view='published',hasMore=false,loading=0,detailLoad=0,reviewBusy=false;const listNode=root.querySelector('#feature-list');const message=error=>root.querySelector('#feature-message').textContent=error.message||error;
 const run=async(button,fn)=>{button.disabled=true;try{await fn();}catch(e){message(e);}finally{button.disabled=false;}};
 async function load(more=false){const current=++loading;try{const data=await api(view==='pending'?'?view=pending&offset='+(more?requests.length:0):'');if(current!==loading||root.querySelector('#feature-list')!==listNode)return;requests=more?[...requests,...data.requests]:data.requests;admin=data.admin;hasMore=Boolean(data.hasMore);root.querySelector('#feature-filters').innerHTML=`<button type="button" data-view="published" aria-pressed="${view==='published'}">Published ideas</button>${token()?`<button type="button" data-view="mine" aria-pressed="${view==='mine'}">My requests</button>`:''}${admin?`<button type="button" data-view="pending" aria-pressed="${view==='pending'}">Awaiting review (${data.counts?.pending??0})</button>`:''}`;root.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;detailLoad++;root.querySelector('#feature-detail').innerHTML='';void load();});root.querySelector('#feature-visibility').textContent=view==='pending'?'Owner review: these requests are private. Open an idea and choose Publish & Open Voting to share it with everyone.':view==='mine'?'Your unpublished requests stay private until the owner reviews them.':'Published ideas are visible to everyone. Sign in to vote and join the discussion.';root.querySelector('#feature-more').hidden=!hasMore;render();}catch(e){message(e);}}
 root.querySelector('#feature-more').onclick=e=>run(e.target,()=>load(true));
 function render(){const q=root.querySelector('#feature-search').value.toLowerCase(), list=root.querySelector('#feature-list');list.innerHTML=requests.filter(r=>(view==='pending'?!r.published:view==='mine'?r.own:r.published)&&(r.title+' '+r.body).toLowerCase().includes(q)).map(r=>`<article class="support-message"><button data-open="${r.id}" class="support-thread-button"><strong>${escape(r.title)}</strong><small>${escape(r.status)}${r.published?'':' · Awaiting publication'} · ${r.votes} votes · ${r.comments} comments</small></button><p>${escape(r.body)}</p><small>${escape(r.author)}</small> ${token()&&r.published?`<button data-vote="${r.id}">${r.voted?'▲ Voted':'△ Vote'}</button>`:''}</article>`).join('')||'<p>No matching requests in this view.</p>';list.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>void detail(b.dataset.open));list.querySelectorAll('[data-vote]').forEach(b=>b.onclick=()=>run(b,async()=>{const r=requests.find(r=>r.id===b.dataset.vote);await api('/'+r.id+'/vote','PUT',{voted:!r.voted});await load();}));}
 async function detail(id){const currentDetail=++detailLoad;const r=requests.find(r=>r.id===id), panel=root.querySelector('#feature-detail');if(!r){panel.innerHTML='';return;}panel.innerHTML=`<h3>${escape(r.title)}</h3>${admin?`<form id="feature-review"><label>Status <select>${['Under review','Planned','In progress','Released'].map(s=>`<option ${s===r.status?'selected':''}>${s}</option>`).join('')}</select></label><p class="feature-board-review-note">${r.published?'Public · Voting open. Unpublishing hides this request and preserves its votes and comments.':'Private · Awaiting review. Publishing makes this idea visible in the app and opens voting.'}</p><div class="feature-review-actions"><button type="submit" class="support-send-btn">${r.published?'Save status':'Publish & Open Voting'}</button>${r.published?'<button type="submit" data-unpublish="true">Unpublish</button>':''}</div></form>`:''}<div id="feature-comments">Loading comments…</div>`;
 panel.querySelector('#feature-review')?.addEventListener('submit',e=>{e.preventDefault();if(reviewBusy)return;reviewBusy=true;const reviewButtons=[...e.target.querySelectorAll('button')];reviewButtons.forEach(b=>b.disabled=true);void run(e.submitter||reviewButtons[0],async()=>{await api('/'+id,'PATCH',{status:e.target.querySelector('select').value,published:e.submitter?.dataset.unpublish!=='true'});message(e.submitter?.dataset.unpublish==='true'?'Request unpublished. Votes and comments are preserved.':'Saved. This request is public and voting is open.');await load();if(view==='pending')panel.innerHTML='';else await detail(id);}).finally(()=>{reviewBusy=false;reviewButtons.forEach(b=>b.disabled=false);});});
 if(!token()){panel.querySelector('#feature-comments').textContent='Sign in to read and join the discussion.';return;}
 try{const data=await api('/'+id+'/comments');if(!panel.isConnected||currentDetail!==detailLoad||root.querySelector('#feature-list')!==listNode)return;const comments=panel.querySelector('#feature-comments');comments.innerHTML=data.comments.map(c=>`<article class="support-message"><strong>${escape(c.author)}${c.developer?' · Developer':''}${admin&&c.reports?' · '+c.reports+' reports':''}</strong><time>${new Date(c.created_at).toLocaleString()}</time>${c.parent_id?`<small>Reply to ${escape(data.comments.find(p=>p.id===c.parent_id)?.author||'a deleted comment')}</small>`:''}<p style="white-space:pre-wrap">${escape(c.body)}</p><button data-reply="${c.id}">Reply</button> ${c.own?`<button data-edit="${c.id}">Edit</button>`:''} ${c.own||admin?`<button data-delete="${c.id}">Delete</button>`:`<button data-report="${c.id}">Report</button>`}</article>`).join('')+`<form class="support-report-form" id="feature-comment"><label for="feature-comment-body">Add a comment</label><textarea id="feature-comment-body" maxlength="3000" required></textarea><button class="support-send-btn">Post comment</button><p role="status"></p></form>`;
 let parentId=null;const form=comments.querySelector('form');comments.querySelectorAll('[data-reply]').forEach(b=>b.onclick=()=>{parentId=b.dataset.reply;form.querySelector('label').textContent='Reply to '+data.comments.find(c=>c.id===parentId).author;form.querySelector('textarea').focus();});
 comments.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>{const c=data.comments.find(c=>c.id===b.dataset.edit), value=prompt('Edit your comment',c.body);if(value!==null)void run(b,async()=>{await api('/'+id+'/comments/'+c.id,'PATCH',{body:value});await detail(id);});});
 comments.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{if(confirm('Delete this comment?'))void run(b,async()=>{await api('/'+id+'/comments/'+b.dataset.delete,'DELETE');await load();await detail(id);});});
 comments.querySelectorAll('[data-report]').forEach(b=>b.onclick=()=>run(b,async()=>{await api('/'+id+'/comments/'+b.dataset.report+'/report','POST',{});b.textContent='Reported';}));
 form.onsubmit=e=>{e.preventDefault();void run(form.querySelector('button'),async()=>{await api('/'+id+'/comments','POST',{body:form.querySelector('textarea').value,parentId});await load();await detail(id);});};
 }catch(e){if(currentDetail===detailLoad&&panel.querySelector('#feature-comments'))panel.querySelector('#feature-comments').textContent=e.message;}}
 root.querySelector('#feature-search').oninput=render;
 root.querySelector('#feature-new')?.addEventListener('submit',e=>{e.preventDefault();void run(e.target.querySelector('button'),async()=>{await api('','POST',{title:root.querySelector('#feature-title').value,body:root.querySelector('#feature-body').value});e.target.reset();message('Submitted. Your request is awaiting review.');await load();});});
 await load();
}

