import { getNutritionProfile, saveNutritionProfile } from "../nutrition/nutrition-storage.js?v=onboarding-1";
import { feetAndInchesToCm, poundsToKg } from "../nutrition/tdee-calculator.js?v=onboarding-1";
import { getAllExercises } from "../workouts/exercise-library.js?v=onboarding-1";
import { getTrainingPreferences, saveTrainingPreferences, markOnboardingComplete, markOnboardingSkipped, onboardingIsHandled } from "../core/training-preferences.js?v=onboarding-1";
import { getUnitPreferences, setUnitPreferences, poundsToKilograms, kilogramsToPounds, inchesToCentimeters, centimetersToInches } from "../core/unit-system.js?v=granular-units-1";
import { renderMusclePriorityChoice } from "../workouts/muscle-priority-visual.js?v=female-back-regions-1";
import { initializeAcquisitionTracking, saveReportedSource, trackProductEvent } from "../analytics/acquisition.js?v=workout-analytics-reconcile-1";
import { APPEARANCE_THEMES, applyAppearanceTheme, getAppearanceTheme, resolveAppearanceTheme } from "../core/appearance-theme.js?v=appearance-themes-3";

const WEIGHT_KEY="forge_weight_entries",ONBOARDING_TOTAL=8;
const PRIMARY_GOALS=[
 ["build_muscle","Build muscle","Add size with balanced hypertrophy training."],
 ["lose_fat_maintain_muscle","Lose body fat","Support fat loss while protecting strength and muscle."],
 ["maintain_muscle","Recomposition","Improve body composition with a steady approach."],
 ["build_strength","Get stronger","Prioritize measurable progress on your main lifts."],
 ["track_training","Maintain & perform","Stay consistent and see what is improving."]
];
const EXPERIENCES=[
 ["new","New to lifting","Less than 1 year","Simple progression and extra guidance."],
 ["intermediate","Some experience","1–3 years","Balanced volume with room to progress."],
 ["experienced","Experienced","3–5 years","More flexibility and targeted volume."],
 ["advanced","Advanced","5+ years","Fine control for an established lifter."]
];
const TRAINING_SETUPS=[
 ["full_gym","Commercial gym","Full equipment",["Full Gym"]],
 ["home_gym","Home gym","Weights at home",["Dumbbells","Barbell","Bodyweight"]],
 ["minimal","Minimal equipment","Dumbbells + bodyweight",["Dumbbells","Bodyweight"]],
 ["bodyweight","Bodyweight","No equipment required",["Bodyweight"]]
];
const ACQUISITION_SOURCES=[["instagram","Instagram"],["tiktok","TikTok"],["youtube","YouTube"],["reddit","Reddit"],["google_search","Google"],["friend_family","Friend"],["app_recommendation","App recommendation"],["other","Other"]];
const MUSCLES=["Chest","Back","Shoulders","Biceps","Triceps","Quads","Hamstrings","Glutes","Calves","Abs"];
const MEANINGFUL_ARRAY_KEYS=["forge_workout_plans","forge_workout_sessions","forge_weight_entries","forge_custom_exercises","level_up_body_measurements","level_up_sleep_entries","level_up_nutrition_phases","level_up_water_entries"];
const MEANINGFUL_OBJECT_KEYS=["level_up_nutrition_habits","level_up_nutrition_macro","level_up_training_preferences"];
const FEATURED_THEMES=["level-up","arctic","system"];
let overlay=null,step=0,manualLaunch=false,answers=null,completionStorageWarning=false;

export function initializeFirstRunOnboarding(){
 ensureStyles();
 if(onboardingIsHandled())return false;
 if(hasMeaningfulExistingUserData()){markOnboardingComplete({migrated:true});return false}
 openOnboarding({manual:false});return true;
}
export function openOnboarding({manual=true}={}){
 ensureStyles();closeOnboarding();manualLaunch=Boolean(manual);step=0;completionStorageWarning=false;answers=loadAnswers();
 overlay=document.createElement("div");overlay.className="levelup-onboarding levelup-onboarding-v2";overlay.setAttribute("role","dialog");overlay.setAttribute("aria-modal","true");overlay.setAttribute("aria-label","Set up Level Up");
 overlay.addEventListener("click",handleClick);overlay.addEventListener("input",handleInput);overlay.addEventListener("change",handleInput);
 document.body.appendChild(overlay);document.body.classList.add("levelup-onboarding-open");render();
}
function closeOnboarding(){overlay?.remove();overlay=null;delete window.__levelUpAnatomySexPreview;document.body.classList.remove("levelup-onboarding-open")}
function ensureStyles(){
 if(!document.querySelector('link[href*="css/onboarding.css"]')){const l=document.createElement("link");l.rel="stylesheet";l.href="css/onboarding.css?v=professional-onboarding-1";document.head.appendChild(l)}
 if(!document.querySelector('link[href*="css/onboarding-granular-units.css"]')){const l=document.createElement("link");l.rel="stylesheet";l.href="css/onboarding-granular-units.css?v=granular-units-1";document.head.appendChild(l)}
}
function readJson(key){try{return JSON.parse(localStorage.getItem(key)||"null")}catch{return null}}
function hasMeaningfulExistingUserData(){
 const profile=readJson("level_up_nutrition_profile");if(profile&&(Number(profile.age)>0||Number(profile.weightLb)>0||Number(profile.heightCm)>0))return true;
 if(MEANINGFUL_ARRAY_KEYS.some(key=>{const v=readJson(key);return Array.isArray(v)&&v.length>0}))return true;
 if(MEANINGFUL_OBJECT_KEYS.some(key=>{const v=readJson(key);return v&&typeof v==="object"&&!Array.isArray(v)&&Object.values(v).some(x=>x!==null&&x!==undefined&&x!==""&&x!==false)}))return true;
 const goal=readJson("level_up_nutrition_goal"),plan=readJson("level_up_nutrition_plan"),schedule=readJson("level_up_workout_schedule_v1"),workout=readJson("level_up_active_workout"),current=readJson("level_up_current_goal");
 if(goal?.goalId||Number(plan?.calculatedCalories)>0||Number(plan?.currentCalories)>0||schedule?.planId)return true;
 if(workout&&typeof workout==="object"&&Object.keys(workout).length)return true;
 if(current&&typeof current==="object"&&Object.keys(current).length)return true;
 try{if(Number(localStorage.getItem("level_up_goal_weight"))>0)return true}catch{}return false;
}
function loadAnswers(){
 const prefs=getTrainingPreferences(),profile=getNutritionProfile()||{},acquisition=readJson("level_up_acquisition_reported")||{};
 const equipment=Array.isArray(prefs.equipment)&&prefs.equipment.length?prefs.equipment:["Full Gym"];
 const trainingSetup=TRAINING_SETUPS.find(([, , ,items])=>items.length===equipment.length&&items.every(x=>equipment.includes(x)))?.[0]||"full_gym";
 const theme=getAppearanceTheme();
 return{displayName:String(profile.displayName||"").slice(0,40),theme,showAllThemes:!FEATURED_THEMES.includes(theme),primaryGoal:prefs.primaryGoal||"",unitPreferences:getUnitPreferences(),age:value(profile.age),sex:profile.sex||"",heightFeet:value(profile.heightFeet),heightInches:value(profile.heightInches),heightCm:value(profile.heightCm),weightLb:value(profile.weightLb),weightKg:value(profile.weightKg),experience:prefs.experience||"",priorities:[...prefs.priorities],days:prefs.days||4,duration:prefs.duration||60,trainingSetup,equipment,limitationMode:prefs.excludedIds.length?"choose":"none",excludedIds:[...prefs.excludedIds],exerciseSearch:"",acquisitionSource:acquisition.source||"",acquisitionOther:acquisition.otherText||""};
}
function value(v){return v===undefined||v===null?"":String(v)}
function chapter(i){return i<=2?"YOUR GOAL":i<=4?"YOUR TRAINING":i<=6?"PERSONALIZE":"YOUR APP"}
function render(){
 if(!overlay||!answers)return;const done=step===ONBOARDING_TOTAL,pos=Math.max(1,step);
 overlay.innerHTML=`<div class="levelup-onboarding-shell"><header class="levelup-onboarding-topbar"><div><span class="eyebrow">${done?"YOUR PLAN":chapter(step)}</span>${done||step===0?"":`<strong>${pos} of ${ONBOARDING_TOTAL-1}</strong>`}</div><button class="levelup-onboarding-skip" type="button" data-onboarding-skip>${done||(manualLaunch&&getTrainingPreferences().onboardingComplete)?"Close":"Explore first"}</button></header>${done||step===0?"":`<div class="levelup-onboarding-progress" aria-label="Setup progress"><span style="width:${pos/(ONBOARDING_TOTAL-1)*100}%"></span></div>`}<main class="levelup-onboarding-body">${done?renderCompletion():renderScreen(step)}</main>${renderFooter()}</div>`;
 updateContinueState();if(step===6&&answers.limitationMode==="choose")renderExerciseResults();
}
function renderScreen(i){return i===0?welcome():i===1?goals():i===2?experience():i===3?schedule():i===4?profile():i===5?priorities():i===6?preferences():appearance()}
function welcome(){return `<section class="onboarding-screen onboarding-welcome"><div class="onboarding-brand-lockup"><img src="assets/level-up-logo.svg" alt=""><span>LEVEL UP</span></div><div class="onboarding-screen-intro"><span class="eyebrow">TRAINING · NUTRITION · RECOVERY</span><h1>Everything you need to level up.</h1><p>Your training, nutrition and recovery—working together in one personalized plan.</p></div>${progressPreview()}<div class="onboarding-feature-strip"><span><i>✓</i>Personalized training</span><span><i>✓</i>Meaningful progress</span><span><i>✓</i>Smarter recovery</span></div><div class="onboarding-welcome-actions"><button class="primary-btn" type="button" data-onboarding-start>${manualLaunch?"Review My Setup":"Build My Plan"}</button><button class="secondary-btn" type="button" data-onboarding-skip>Explore First</button></div></section>`}
function progressPreview(){return `<div class="onboarding-progress-preview" aria-label="Example Level Up progress. Preview data only."><div class="onboarding-preview-head"><div><span>EXAMPLE PROGRESS</span><strong>Momentum is building</strong></div><b>12 WEEKS</b></div><div class="onboarding-preview-grid"><article><div class="onboarding-preview-label"><span>Estimated 1RM</span><strong>+16%</strong></div><b>215 <small>lb</small></b><svg viewBox="0 0 164 66" role="img" aria-label="Example estimated one rep max increasing"><path class="preview-gridline" d="M2 54H162M2 32H162M2 10H162"/><path class="preview-area" d="M3 53 C25 52 34 48 51 47 S81 37 98 38 S126 27 161 13 L161 64 L3 64Z"/><path class="preview-line" pathLength="1" d="M3 53 C25 52 34 48 51 47 S81 37 98 38 S126 27 161 13"/><circle cx="161" cy="13" r="4"/></svg></article><article><div class="onboarding-preview-label"><span>Weight trend</span><strong>On track</strong></div><b>181.4 <small>lb</small></b><svg viewBox="0 0 164 66" role="img" aria-label="Example body-weight trend"><path class="preview-gridline" d="M2 54H162M2 32H162M2 10H162"/><path class="preview-daily" d="M3 51 L19 42 L35 47 L51 34 L67 38 L83 30 L99 34 L115 22 L131 27 L147 17 L161 20"/><path class="preview-trend" pathLength="1" d="M3 48 C36 44 55 40 82 34 S127 24 161 19"/><circle cx="161" cy="19" r="4"/></svg></article></div><p>Preview data shows how Level Up turns workouts and weigh-ins into useful trends.</p></div>`}
function intro(eyebrow,title,copy){return `<div class="onboarding-screen-intro"><span class="eyebrow">${eyebrow}</span><h2>${title}</h2><p>${copy}</p></div>`}
function goals(){return `<section class="onboarding-screen onboarding-goal-screen">${intro("START WITH THE OUTCOME","What do you want Level Up to help you achieve?","Your answer shapes training emphasis and your starting nutrition strategy.")}<div class="onboarding-goal-grid">${PRIMARY_GOALS.map(([v,l,d])=>`<button class="onboarding-goal-card ${answers.primaryGoal===v?"selected":""}" type="button" data-choice-group="goal" data-choice-value="${v}">${goalIcon(v)}<span><strong>${l}</strong><small>${d}</small></span><i>✓</i></button>`).join("")}</div></section>`}
function goalIcon(v){const p={build_muscle:'<path d="M4 9v6M7 7v10M17 7v10M20 9v6M7 12h10"/>',lose_fat_maintain_muscle:'<path d="M5 7h14M7 7l1 12h8l1-12M9 11h6M10 15h4"/>',maintain_muscle:'<path d="M4 12h5l2-5 3 10 2-5h4M7 20h10"/>',build_strength:'<path d="M4 9v6M7 7v10M17 7v10M20 9v6M7 12h10"/>',track_training:'<path d="M5 19V9M10 19V5M15 19v-7M20 19V3"/>'};return `<span class="onboarding-goal-icon"><svg viewBox="0 0 24 24">${p[v]}</svg></span>`}
function experience(){return `<section class="onboarding-screen onboarding-experience-screen">${intro("MATCH YOUR EXPERIENCE","Where are you in your training journey?","Level Up adjusts complexity, exercise selection and guidance to meet you where you are.")}<div class="onboarding-level-track"><span></span><i></i><i></i><i></i><i></i></div><div class="onboarding-experience-list">${EXPERIENCES.map(([v,l,d,e],i)=>`<button class="onboarding-experience-card ${answers.experience===v?"selected":""}" type="button" data-choice-group="experience" data-choice-value="${v}"><b>${String(i+1).padStart(2,"0")}</b><span><strong>${l}</strong><small>${d}</small><em>${e}</em></span><i>✓</i></button>`).join("")}</div></section>`}
function schedule(){return `<section class="onboarding-screen onboarding-schedule-screen">${intro("BUILD AROUND YOUR LIFE","What can you realistically sustain?","Your program will fit your schedule and the equipment you can reliably use.")}<div class="onboarding-week-preview"><div><span>Your training week</span><strong>${answers.days} sessions · ${answers.duration===90?"90+":answers.duration} min</strong></div><div class="onboarding-week-dots">${["M","T","W","T","F","S","S"].map((d,i)=>`<span class="${i<answers.days?"active":""}">${d}</span>`).join("")}</div></div><h3>Days per week</h3><div class="onboarding-number-row">${[2,3,4,5,6].map(v=>`<button class="onboarding-chip ${answers.days===v?"selected":""}" type="button" data-days="${v}">${v}</button>`).join("")}</div><h3>Typical workout length</h3><div class="onboarding-chip-grid onboarding-duration-grid">${[30,45,60,75,90].map(v=>`<button class="onboarding-chip ${answers.duration===v?"selected":""}" type="button" data-duration="${v}">${v===90?"90+":v}<small>min</small></button>`).join("")}</div><h3>Where do you train?</h3><div class="onboarding-setup-grid">${TRAINING_SETUPS.map(([v,l,d])=>`<button class="onboarding-setup-card ${answers.trainingSetup===v?"selected":""}" type="button" data-training-setup="${v}"><span>${v==="full_gym"?"▦":v==="home_gym"?"⌂":v==="minimal"?"▰":"●"}</span><strong>${l}</strong><small>${d}</small><i>✓</i></button>`).join("")}</div></section>`}
function profile(){
 const u=answers.unitPreferences,mh=u.length==="cm",mw=u.bodyWeight==="kg";
 return `<section class="onboarding-screen onboarding-profile-screen">${intro("PERSONAL STARTING POINT","A few details to make it yours.","These help calculate starting targets and select the right anatomy. Flexible units mean pounds and kilometres are fully supported, and everything remains editable.")}<div class="onboarding-profile-note"><span>⌁</span><p><strong>Private by design</strong>Your details are never shown publicly.</p></div><div class="onboarding-profile-grid"><label class="onboarding-profile-wide">What should we call you? <small>(optional)</small><input data-answer="displayName" type="text" autocomplete="nickname" maxlength="40" value="${esc(answers.displayName)}" placeholder="Name or username"></label><label>Age<input data-answer="age" type="number" inputmode="numeric" min="18" max="100" value="${esc(answers.age)}" placeholder="Age"></label><label>Anatomy<select data-answer="sex"><option value="">Choose</option><option value="male" ${answers.sex==="male"?"selected":""}>Male</option><option value="female" ${answers.sex==="female"?"selected":""}>Female</option></select></label>${mh?`<label class="onboarding-profile-wide">Height (cm)<input data-unit-input-ignore data-answer="heightCm" type="number" inputmode="decimal" min="90" max="250" step=".1" value="${esc(answers.heightCm)}" placeholder="Height"></label>`:`<label>Height (ft)<input data-unit-input-ignore data-answer="heightFeet" type="number" inputmode="numeric" min="3" max="8" value="${esc(answers.heightFeet)}" placeholder="5"></label><label>Height (in)<input data-unit-input-ignore data-answer="heightInches" type="number" inputmode="decimal" min="0" max="11" step=".1" value="${esc(answers.heightInches)}" placeholder="10"></label>`}${mw?`<label class="onboarding-profile-wide">Weight (kg)<input data-unit-input-ignore data-answer="weightKg" type="number" inputmode="decimal" min="1" step=".1" value="${esc(answers.weightKg)}" placeholder="Weight"></label>`:`<label class="onboarding-profile-wide">Weight (lb)<input data-unit-input-ignore data-answer="weightLb" type="number" inputmode="decimal" min="1" step=".1" value="${esc(answers.weightLb)}" placeholder="Weight"></label>`}</div><details class="onboarding-units-disclosure"><summary>Measurement preferences <span>${u.bodyWeight} · ${u.distance} · ${u.length}</span></summary><div class="onboarding-unit-preferences" data-unit-text-ignore>${unitChoice("bodyWeight","Body weight",[["lb","lb"],["kg","kg"]])}${unitChoice("liftingWeight","Workout weights",[["lb","lb"],["kg","kg"]])}${unitChoice("distance","Cardio distance",[["km","Kilometres"],["mi","Miles"]])}${unitChoice("length","Height & measurements",[["cm","cm"],["in","ft / in"]])}</div></details></section>`;
}
function priorities(){return `<section class="onboarding-screen onboarding-priority-screen">${intro("CHOOSE YOUR FOCUS","What do you especially want to improve?","Tap up to three areas. Level Up will emphasize them while keeping your program balanced.")}<div class="onboarding-priority-status"><strong>${answers.priorities.length?`${answers.priorities.length} selected`:"Balanced development"}</strong><span>${answers.priorities.length?answers.priorities.join(" · "):"No priority muscles selected"}</span></div><div class="muscle-priority-grid">${MUSCLES.map(m=>renderMusclePriorityChoice(m,answers.priorities.includes(m))).join("")}</div><button class="onboarding-no-priority ${answers.priorities.length===0?"selected":""}" type="button" data-no-priority>No particular priority</button></section>`}
function preferences(){return `<section class="onboarding-screen onboarding-preference-screen">${intro("TRAIN YOUR WAY","Anything you would prefer to avoid?","Level Up can swap exercises while preserving the purpose of your program.")}<div class="onboarding-swap-preview"><span><small>PROGRAMMED</small><strong>Barbell squat</strong></span><i>→</i><span><small>SMART SWAP</small><strong>Leg press</strong></span></div><div class="onboarding-option-stack onboarding-limit-options">${choice("limitations","none","No preferences or limitations",answers.limitationMode==="none","Use the best-matched exercises.")}${choice("limitations","choose","Choose exercises to avoid",answers.limitationMode==="choose","Search your exercise library.")}</div>${answers.limitationMode==="choose"?`<div class="onboarding-exercise-picker"><input id="onboarding-exercise-search" type="search" value="${esc(answers.exerciseSearch)}" placeholder="Search exercise, muscle or equipment"><div class="onboarding-selected-exercises">${selectedExercises()}</div><div id="onboarding-exercise-results" class="onboarding-exercise-results"></div></div>`:""}<p class="onboarding-safety-note">Exercise preferences are not a medical screening. Stop if an exercise causes pain.</p></section>`}
function appearance(){
 const themes=answers.showAllThemes?APPEARANCE_THEMES:APPEARANCE_THEMES.filter(t=>FEATURED_THEMES.includes(t.id));
 return `<section class="onboarding-screen onboarding-appearance-screen">${intro("MAKE LEVEL UP YOURS","Choose your appearance.","Each preview is live. Your choice applies throughout the app and can be changed anytime.")}<div class="onboarding-theme-grid" role="radiogroup" aria-label="App appearance">${themes.map(themeCard).join("")}</div>${answers.showAllThemes?"":'<button class="onboarding-show-themes" type="button" data-show-themes>See all appearances</button>'}<div class="onboarding-ready-preview"><span>✓</span><p><strong>Ready for your plan</strong>Your goal, schedule, equipment and preferences are set.</p></div></section>`;
}
function themeCard(t){const s=answers.theme===t.id,e=resolveAppearanceTheme(t.id);return `<button class="onboarding-theme-card theme-preview-${t.id}${s?" selected":""}" type="button" role="radio" aria-checked="${s}" data-onboarding-theme="${t.id}"><span class="onboarding-theme-check">✓</span><span class="appearance-theme-preview" data-preview-effective="${e}"><i class="appearance-preview-top"></i><i class="appearance-preview-card"><b></b><em></em><small></small></i><i class="appearance-preview-nav"></i></span><strong>${esc(t.name)}</strong><small>${esc(t.description)}</small></button>`}
function unitChoice(kind,label,options){return `<div class="onboarding-unit-row"><strong>${label}</strong><div role="radiogroup" aria-label="${label}">${options.map(([v,t])=>`<button type="button" data-unit-kind="${kind}" data-unit-value="${v}" class="${answers.unitPreferences[kind]===v?"selected":""}" aria-pressed="${answers.unitPreferences[kind]===v}">${t}</button>`).join("")}</div></div>`}
function choice(group,value,label,selected,detail=""){return `<button class="onboarding-option ${selected?"selected":""}" type="button" data-choice-group="${group}" data-choice-value="${esc(value)}"><strong>${esc(label)}</strong>${detail?`<small>${esc(detail)}</small>`:""}<i>✓</i></button>`}
function renderFooter(){if(step===0||step===ONBOARDING_TOTAL)return"";return `<footer class="levelup-onboarding-footer"><button class="secondary-btn" type="button" data-onboarding-back>Back</button><button class="primary-btn" type="button" data-onboarding-next>${step===ONBOARDING_TOTAL-1?"Create My Plan":"Continue"}</button></footer>`}
function renderCompletion(){
 const goal=PRIMARY_GOALS.find(([v])=>v===answers.primaryGoal)?.[1]||"Personal progress",exp=EXPERIENCES.find(([v])=>v===answers.experience)?.[1]||"Personalized",setup=TRAINING_SETUPS.find(([v])=>v===answers.trainingSetup)?.[1]||"Your equipment",priority=answers.priorities.length?answers.priorities.join(" · "):"Balanced development";
 return `<section class="onboarding-screen onboarding-completion"><div class="onboarding-complete-hero"><span class="onboarding-complete-mark">✓</span><span class="eyebrow">BUILT AROUND YOU</span><h2>${answers.displayName?`${esc(answers.displayName)}, your`:"Your"} Level Up plan is ready.</h2><p>A clear starting point that can adapt as you log workouts, recovery, nutrition and progress.</p></div>${completionStorageWarning?'<div class="onboarding-storage-warning"><strong>Your plan is ready.</strong><span>Private browsing blocked some settings from being saved permanently.</span></div>':""}<div class="onboarding-build-sequence"><div><i>✓</i><span><strong>Training schedule</strong><small>${answers.days} days per week · ${answers.duration===90?"90+":answers.duration} minute sessions</small></span></div><div><i>✓</i><span><strong>Program direction</strong><small>${esc(goal)} · ${esc(exp)}</small></span></div><div><i>✓</i><span><strong>Equipment & focus</strong><small>${esc(setup)} · ${esc(priority)}</small></span></div><div><i>✓</i><span><strong>Nutrition & recovery</strong><small>Starting targets and recovery trends unlock as you log</small></span></div></div><div class="onboarding-plan-preview"><div class="onboarding-plan-preview-head"><span>YOUR STARTING POINT</span><b>PERSONALIZED</b></div><div class="onboarding-plan-metrics"><div><span>Training</span><strong>${answers.days}×</strong><small>per week</small></div><div><span>Focus</span><strong>${answers.priorities.length||"All"}</strong><small>${answers.priorities.length?"priority areas":"muscle groups"}</small></div><div><span>Progress</span><strong>Ready</strong><small>starts with your first log</small></div></div><div class="onboarding-empty-trend"><svg viewBox="0 0 300 68"><path d="M1 57H299M1 31H299M1 5H299"/><path class="empty-trend-path" d="M2 55 C48 52 74 46 105 42 S165 35 201 26 S255 18 298 7"/></svg><p><strong>Your progress starts here.</strong>Complete workouts and weigh-ins to build your personal trends.</p></div></div><div class="onboarding-completion-actions"><button class="primary-btn" type="button" data-onboarding-finish="smart">Build My Workout Program</button><button class="secondary-btn" type="button" data-onboarding-finish="templates">Choose a Template</button><button class="onboarding-text-action" type="button" data-onboarding-finish="home">Explore the App</button></div><details class="onboarding-acquisition"><summary>Help us improve Level Up <span>Optional</span></summary><p>How did you hear about us?</p><div>${ACQUISITION_SOURCES.map(([v,l])=>`<button type="button" class="${answers.acquisitionSource===v?"selected":""}" data-choice-group="acquisition" data-choice-value="${v}">${l}</button>`).join("")}</div>${answers.acquisitionSource==="other"?`<label>Where did you hear about us?<input data-answer="acquisitionOther" type="text" maxlength="80" value="${esc(answers.acquisitionOther)}" placeholder="Podcast, creator, gym, website…"></label>`:""}</details></section>`;
}
function handleClick(e){
 const b=e.target.closest("button");if(!b||!overlay?.contains(b))return;
 if(b.matches("[data-onboarding-skip]"))return skipOnboarding();
 if(b.matches("[data-onboarding-start]")){step=1;return render()}
 if(b.matches("[data-onboarding-back]")){step=Math.max(0,step-1);return render()}
 if(b.matches("[data-onboarding-next]")){if(!valid(step))return;if(step===ONBOARDING_TOTAL-1)return complete();step++;return render()}
 if(b.matches("[data-show-themes]")){answers.showAllThemes=true;return render()}
 if(b.dataset.onboardingTheme){answers.theme=b.dataset.onboardingTheme;applyAppearanceTheme(answers.theme);return render()}
 if(b.dataset.unitKind&&b.dataset.unitValue){changeUnit(b.dataset.unitKind,b.dataset.unitValue);return render()}
 if(b.dataset.choiceGroup){applyChoice(b.dataset.choiceGroup,b.dataset.choiceValue);if(b.dataset.choiceGroup==="acquisition"&&step===ONBOARDING_TOTAL)void saveReportedSource(answers.acquisitionSource,answers.acquisitionOther);return render()}
 if(b.dataset.trainingSetup){const x=TRAINING_SETUPS.find(([v])=>v===b.dataset.trainingSetup);if(x){answers.trainingSetup=x[0];answers.equipment=[...x[3]]}return render()}
 if(b.dataset.priority){togglePriority(b.dataset.priority);return render()}
 if(b.matches("[data-no-priority]")){answers.priorities=[];return render()}
 if(b.dataset.days){answers.days=Number(b.dataset.days);return render()}
 if(b.dataset.duration){answers.duration=Number(b.dataset.duration);return render()}
 if(b.dataset.avoidAdd){if(!answers.excludedIds.includes(b.dataset.avoidAdd))answers.excludedIds.push(b.dataset.avoidAdd);return render()}
 if(b.dataset.avoidRemove){answers.excludedIds=answers.excludedIds.filter(id=>id!==b.dataset.avoidRemove);return render()}
 if(b.dataset.onboardingFinish)finishRoute(b.dataset.onboardingFinish);
}
function handleInput(e){const f=e.target;if(f.dataset?.answer)answers[f.dataset.answer]=f.value;if(f.dataset?.answer==="sex"){window.__levelUpAnatomySexPreview=answers.sex;window.dispatchEvent(new CustomEvent("levelup:profile-updated"))}if(f.dataset?.answer==="acquisitionOther"&&answers.acquisitionSource==="other")void saveReportedSource(answers.acquisitionSource,answers.acquisitionOther);if(f.id==="onboarding-exercise-search"){answers.exerciseSearch=f.value;renderExerciseResults()}updateContinueState()}
function changeUnit(kind,v){const ok={bodyWeight:["lb","kg"],liftingWeight:["lb","kg"],distance:["km","mi"],length:["cm","in"]};if(!ok[kind]?.includes(v))return;if(kind==="length"&&v==="cm"){const n=Number(answers.heightFeet)*12+Number(answers.heightInches);if(n>0)answers.heightCm=String(Math.round(inchesToCentimeters(n)*10)/10)}if(kind==="length"&&v==="in"){const cm=Number(answers.heightCm);if(cm>0){const n=centimetersToInches(cm);answers.heightFeet=String(Math.floor(n/12));answers.heightInches=String(Math.round(n%12*10)/10)}}if(kind==="bodyWeight"&&v==="kg"&&Number(answers.weightLb)>0)answers.weightKg=String(Math.round(poundsToKilograms(Number(answers.weightLb))*10)/10);if(kind==="bodyWeight"&&v==="lb"&&Number(answers.weightKg)>0)answers.weightLb=String(Math.round(kilogramsToPounds(Number(answers.weightKg))*10)/10);answers.unitPreferences={...answers.unitPreferences,[kind]:v}}
function applyChoice(g,v){if(g==="goal")answers.primaryGoal=v;if(g==="experience")answers.experience=v;if(g==="limitations"){answers.limitationMode=v;if(v==="none")answers.excludedIds=[]}if(g==="acquisition"){answers.acquisitionSource=v;if(v!=="other")answers.acquisitionOther=""}}
function togglePriority(m){answers.priorities=answers.priorities.includes(m)?answers.priorities.filter(x=>x!==m):answers.priorities.length<3?[...answers.priorities,m]:answers.priorities}
function valid(i){if(i===1)return!!answers.primaryGoal;if(i===2)return!!answers.experience;if(i===3)return[2,3,4,5,6].includes(Number(answers.days))&&[30,45,60,75,90].includes(Number(answers.duration))&&TRAINING_SETUPS.some(([v])=>v===answers.trainingSetup);if(i===4){const age=Number(answers.age),mh=answers.unitPreferences.length==="cm",mw=answers.unitPreferences.bodyWeight==="kg",ft=Number(answers.heightFeet),inch=Number(answers.heightInches),cm=Number(answers.heightCm),w=Number(mw?answers.weightKg:answers.weightLb),height=mh?cm>=90&&cm<=250:ft>=3&&ft<=8&&inch>=0&&inch<=11;return age>=18&&age<=100&&["male","female"].includes(answers.sex)&&height&&w>0}if(i===7)return APPEARANCE_THEMES.some(t=>t.id===answers.theme);return true}
function updateContinueState(){const b=overlay?.querySelector("[data-onboarding-next]");if(b)b.disabled=!valid(step)}
function complete(){
 const age=Number(answers.age),mh=answers.unitPreferences.length==="cm",mw=answers.unitPreferences.bodyWeight==="kg",heightCm=mh?Number(answers.heightCm):feetAndInchesToCm(Number(answers.heightFeet),Number(answers.heightInches)),ti=centimetersToInches(heightCm),feet=mh?Math.floor(ti/12):Number(answers.heightFeet),inches=mh?Number((ti-feet*12).toFixed(1)):Number(answers.heightInches),weightLb=mw?kilogramsToPounds(Number(answers.weightKg)):Number(answers.weightLb),weightKg=poundsToKg(weightLb);let failed=false;const attempt=fn=>{try{fn()}catch(err){failed=true;console.warn("Level Up onboarding storage write failed",err)}};
 attempt(()=>saveNutritionProfile({...getNutritionProfile(),displayName:String(answers.displayName||"").trim().slice(0,40),age,sex:answers.sex,heightFeet:feet,heightInches:inches,weightLb,heightCm,weightKg}));attempt(()=>setUnitPreferences(answers.unitPreferences));attempt(()=>saveInitialWeight(weightLb));attempt(()=>saveTrainingPreferences({primaryGoal:answers.primaryGoal,experience:answers.experience,priorities:answers.priorities,days:Number(answers.days),duration:Number(answers.duration),trainingSetup:answers.trainingSetup,equipment:answers.equipment,excludedIds:answers.limitationMode==="choose"?answers.excludedIds:[]}));attempt(()=>markOnboardingComplete({migrated:false}));
 if(answers.acquisitionSource)void saveReportedSource(answers.acquisitionSource,answers.acquisitionOther);void trackProductEvent("onboarding_completed",{eventKey:"onboarding-v2",metadata:{primaryGoal:answers.primaryGoal,experience:answers.experience,days:Number(answers.days),trainingSetup:answers.trainingSetup}});completionStorageWarning=failed;window.dispatchEvent(new CustomEvent("levelup:nutrition-updated"));step=ONBOARDING_TOTAL;render();
}
function saveInitialWeight(weight){const entries=readJson(WEIGHT_KEY);if(Array.isArray(entries)&&entries.length)return;const n=new Date(),date=`${n.getFullYear()}-${String(n.getMonth()+1).padStart(2,"0")}-${String(n.getDate()).padStart(2,"0")}`;localStorage.setItem(WEIGHT_KEY,JSON.stringify([{date,weight:Math.round(Number(weight)*10)/10}]))}
function skipOnboarding(){let prefs={};try{prefs=getTrainingPreferences()}catch{}if(!prefs.onboardingComplete)try{markOnboardingSkipped()}catch{}closeOnboarding()}
function finishRoute(dest){closeOnboarding();if(dest==="home")return document.querySelector('.nav-btn[data-page="home"]')?.click();document.querySelector('.nav-btn[data-page="workout"]')?.click();setTimeout(()=>{if(dest==="smart")document.querySelector("[data-smart-build]")?.click();if(dest==="templates")document.querySelector("[data-template-build]")?.click()},80)}
function selectedExercises(){const map=new Map(getAllExercises().map(x=>[x.id,x]));return answers.excludedIds.length?answers.excludedIds.map(id=>`<button class="onboarding-selected-exercise" type="button" data-avoid-remove="${esc(id)}">${esc(map.get(id)?.name||id)} ×</button>`).join(""):'<small class="onboarding-helper">No exercises selected.</small>'}
function renderExerciseResults(){const host=overlay?.querySelector("#onboarding-exercise-results");if(!host)return;const q=String(answers.exerciseSearch||"").trim().toLowerCase(),selected=new Set(answers.excludedIds),results=getAllExercises().filter(x=>x.trackingType!=="notes"&&!selected.has(x.id)).filter(x=>!q||[x.name,x.muscleGroup,x.equipment].some(v=>String(v||"").toLowerCase().includes(q))).sort((a,b)=>String(a.muscleGroup).localeCompare(String(b.muscleGroup))||String(a.name).localeCompare(String(b.name))).slice(0,12);host.innerHTML=results.length?results.map(x=>`<button class="onboarding-exercise-row" type="button" data-avoid-add="${esc(x.id)}"><span><strong>${esc(x.name)}</strong><small>${esc(x.muscleGroup)} · ${esc(x.equipment)}</small></span><b>Avoid</b></button>`).join(""):'<p class="onboarding-helper">No matching exercises.</p>'}
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
document.addEventListener("levelup:open-profile-setup",()=>openOnboarding({manual:true}));
initializeAcquisitionTracking();
initializeFirstRunOnboarding();
