import { getNutritionProfile, saveNutritionProfile } from "../nutrition/nutrition-storage.js?v=onboarding-1";
import { feetAndInchesToCm, poundsToKg } from "../nutrition/tdee-calculator.js?v=onboarding-1";
import { getAllExercises } from "../workouts/exercise-library.js?v=onboarding-1";
import { getTrainingPreferences, saveTrainingPreferences, markOnboardingComplete, markOnboardingSkipped, onboardingIsHandled } from "../core/training-preferences.js?v=onboarding-1";
import { getUnitPreferences, setUnitPreferences, poundsToKilograms, kilogramsToPounds, inchesToCentimeters, centimetersToInches } from "../core/unit-system.js?v=granular-units-1";
import { renderMusclePriorityChoice } from "../workouts/muscle-priority-visual.js?v=female-back-regions-1";
import { initializeAcquisitionTracking, saveReportedSource, trackProductEvent } from "../analytics/acquisition.js?v=workout-analytics-reconcile-1";
import { APPEARANCE_THEMES, applyAppearanceTheme, getAppearanceTheme, resolveAppearanceTheme } from "../core/appearance-theme.js?v=appearance-themes-3";
import { WEEKDAY_ORDER, defaultTrainingDays, normalizeTrainingDays, trainingDaysForCount } from "../workouts/onboarding-schedule.js?v=onboarding-training-days-1";
import { ACTIVITY_LEVELS, GOAL_PRESETS, calculateTdee } from "../nutrition/tdee-calculator.js?v=nutrition-feature-choice-1";
import { saveNutritionGoal, syncCalculatedCalories } from "../nutrition/nutrition-storage.js?v=nutrition-feature-choice-1";
import { saveNutritionPhase } from "../nutrition/nutrition-phase.js?v=nutrition-feature-choice-1";
import { getMaintenanceUpdateMode, setMaintenanceUpdateMode } from "../nutrition/maintenance-check-in.js?v=calendar-checkin-day-1";
import { setNutritionEnabled } from "../core/app-feature-preferences.js?v=nutrition-feature-choice-1";

const WEIGHT_KEY="forge_weight_entries",MANUAL_TARGET_KEY="level_up_manual_calorie_target_v1";
const PRIMARY_GOALS=[
 ["build_muscle","Build muscle","Add size with balanced hypertrophy training."],
 ["lose_fat_maintain_muscle","Lose body fat","Support fat loss while protecting strength and muscle."],
 ["maintain_muscle","Recomposition","Improve body composition with a steady approach."],
 ["build_strength","Get stronger","Prioritize measurable progress on your main lifts."],
 ["track_training","Maintain & perform","Stay consistent and see what is improving."]
];
const EXPERIENCES=[
 ["new","New to lifting","Less than 1 year","Simple progression and extra guidance."],
 ["intermediate","Some experience","1–3 years","Balanced volume with room to progress."],
 ["experienced","Experienced","3–5 years","More flexibility and targeted volume."],
 ["advanced","Advanced","5+ years","Fine control for an established lifter."]
];
const TRAINING_SETUPS=[
 ["full_gym","Commercial gym","Full equipment",["Full Gym"]],
 ["home_gym","Home gym","Weights at home",["Dumbbells","Barbell","Bodyweight"]],
 ["minimal","Minimal equipment","Dumbbells + bodyweight",["Dumbbells","Bodyweight"]],
 ["bodyweight","Bodyweight","No equipment required",["Bodyweight"]]
];
const ACQUISITION_SOURCES=[["app_recommendation","App Store"],["google_search","Google"],["instagram","Instagram"],["tiktok","TikTok"],["youtube","YouTube"],["reddit","Reddit"],["friend_family","A friend"],["other","Somewhere else"]];
const MUSCLES=["Chest","Back","Shoulders","Biceps","Triceps","Quads","Hamstrings","Glutes","Calves","Abs"];
const MEANINGFUL_ARRAY_KEYS=["forge_workout_plans","forge_workout_sessions","forge_weight_entries","forge_custom_exercises","level_up_body_measurements","level_up_sleep_entries","level_up_nutrition_phases","level_up_water_entries"];
const MEANINGFUL_OBJECT_KEYS=["level_up_nutrition_habits","level_up_nutrition_macro","level_up_training_preferences"];
const FEATURED_THEMES=["level-up","arctic","system"];
const WEEKDAYS={0:["S","Sunday","Sun"],1:["M","Monday","Mon"],2:["T","Tuesday","Tue"],3:["W","Wednesday","Wed"],4:["T","Thursday","Thu"],5:["F","Friday","Fri"],6:["S","Saturday","Sat"]};
let overlay=null,step=0,manualLaunch=false,answers=null,completionStorageWarning=false;

export function initializeFirstRunOnboarding(){
 ensureStyles();
 if(onboardingIsHandled())return false;
 if(hasMeaningfulExistingUserData()){markOnboardingComplete({migrated:true});return false}
 openOnboarding({manual:false});return true;
}
export function openOnboarding({manual=true}={}){
 ensureStyles();closeOnboarding();manualLaunch=Boolean(manual);step=0;completionStorageWarning=false;answers=loadAnswers();
 overlay=document.createElement("div");overlay.className="levelup-onboarding levelup-onboarding-v2";overlay.setAttribute("role","dialog");overlay.setAttribute("aria-modal","true");overlay.setAttribute("aria-label","Set up Level Up");
 overlay.addEventListener("click",handleClick);overlay.addEventListener("input",handleInput);overlay.addEventListener("change",handleInput);
 document.body.appendChild(overlay);document.body.classList.add("levelup-onboarding-open");render();
}
function closeOnboarding(){overlay?.remove();overlay=null;delete window.__levelUpAnatomySexPreview;document.body.classList.remove("levelup-onboarding-open")}
function ensureStyles(){
 if(!document.querySelector('link[href*="css/onboarding.css"]')){const l=document.createElement("link");l.rel="stylesheet";l.href="css/onboarding.css?v=acquisition-step-1";document.head.appendChild(l)}
 if(!document.querySelector('link[href*="css/onboarding-granular-units.css"]')){const l=document.createElement("link");l.rel="stylesheet";l.href="css/onboarding-granular-units.css?v=onboarding-units-step-1";document.head.appendChild(l)}
}
function readJson(key){try{return JSON.parse(localStorage.getItem(key)||"null")}catch{return null}}
function hasMeaningfulExistingUserData(){
 const profile=readJson("level_up_nutrition_profile");if(profile&&(Number(profile.age)>0||Number(profile.weightLb)>0||Number(profile.heightCm)>0))return true;
 if(MEANINGFUL_ARRAY_KEYS.some(key=>{const v=readJson(key);return Array.isArray(v)&&v.length>0}))return true;
 if(MEANINGFUL_OBJECT_KEYS.some(key=>{const v=readJson(key);return v&&typeof v==="object"&&!Array.isArray(v)&&Object.values(v).some(x=>x!==null&&x!==undefined&&x!==""&&x!==false)}))return true;
 const goal=readJson("level_up_nutrition_goal"),plan=readJson("level_up_nutrition_plan"),schedule=readJson("level_up_workout_schedule_v1"),workout=readJson("level_up_active_workout"),current=readJson("level_up_current_goal");
 if(goal?.goalId||Number(plan?.calculatedCalories)>0||Number(plan?.currentCalories)>0||schedule?.planId)return true;
 if(workout&&typeof workout==="object"&&Object.keys(workout).length)return true;
 if(current&&typeof current==="object"&&Object.keys(current).length)return true;
 try{if(Number(localStorage.getItem("level_up_goal_weight"))>0)return true}catch{}return false;
}
function loadAnswers(){
 const prefs=getTrainingPreferences(),profile=getNutritionProfile()||{},acquisition=readJson("level_up_acquisition_reported")||{};
 const equipment=Array.isArray(prefs.equipment)&&prefs.equipment.length?prefs.equipment:["Full Gym"];
 const trainingSetup=TRAINING_SETUPS.find(([, , ,items])=>items.length===equipment.length&&items.every(x=>equipment.includes(x)))?.[0]||"full_gym";
 const theme=getAppearanceTheme(),days=prefs.days||4,trainingDays=trainingDaysForCount(prefs.trainingDays,days);
 const savedMode=getMaintenanceUpdateMode();
 return{displayName:String(profile.displayName||"").slice(0,40),theme,showAllThemes:!FEATURED_THEMES.includes(theme),primaryGoal:prefs.primaryGoal||"",unitPreferences:getUnitPreferences(),age:value(profile.age),sex:profile.sex||"",heightFeet:value(profile.heightFeet),heightInches:value(profile.heightInches),heightCm:value(profile.heightCm),weightLb:value(profile.weightLb),weightKg:value(profile.weightKg),experience:prefs.experience||"",priorities:[...prefs.priorities],days,duration:prefs.duration||60,trainingDays,trainingSetup,equipment,limitationMode:prefs.excludedIds.length?"choose":"none",excludedIds:[...prefs.excludedIds],exerciseSearch:"",trackNutrition:typeof prefs.nutritionEnabled==="boolean"?prefs.nutritionEnabled:null,nutritionActivity:ACTIVITY_LEVELS[profile.activity]?profile.activity:"",nutritionGoalId:suggestNutritionGoal(prefs.primaryGoal),nutritionMode:savedMode==="track"?"manual":"coach",coachUpdateMode:savedMode==="automatic"?"automatic":"review",acquisitionSource:acquisition.source||"",acquisitionOther:acquisition.otherText||""};
}
function value(v){return v===undefined||v===null?"":String(v)}
function screenKeys(){return ["welcome","goal","experience","schedule","units","profile","body-composition","priorities","preferences","nutrition-choice",...(answers?.trackNutrition===true?["nutrition-activity","nutrition-goal","nutrition-mode"]:[]),"appearance","acquisition"]}
function currentScreen(){return screenKeys()[step]}
function chapter(key){return ["goal","experience"].includes(key)?"YOUR GOAL":["schedule","units","profile","body-composition"].includes(key)?"YOUR TRAINING":["priorities","preferences"].includes(key)?"PERSONALIZE":["nutrition-choice","nutrition-activity","nutrition-goal","nutrition-mode"].includes(key)?"YOUR NUTRITION":"YOUR APP"}
function render(){
 if(!overlay||!answers)return;const keys=screenKeys(),done=step===keys.length,pos=Math.max(1,step),total=keys.length-1,key=currentScreen();
 overlay.innerHTML=`<div class="levelup-onboarding-shell"><header class="levelup-onboarding-topbar"><div><span class="eyebrow">${done?"YOUR PLAN":chapter(key)}</span>${done||step===0?"":`<strong>${pos} of ${total}</strong>`}</div><button class="levelup-onboarding-skip" type="button" data-onboarding-skip>${done||(manualLaunch&&getTrainingPreferences().onboardingComplete)?"Close":"Explore first"}</button></header>${done||step===0?"":`<div class="levelup-onboarding-progress" aria-label="Setup progress"><span style="width:${pos/total*100}%"></span></div>`}<main class="levelup-onboarding-body">${done?renderCompletion():renderScreen(key)}</main>${renderFooter()}</div>`;
 updateContinueState();if(key==="preferences"&&answers.limitationMode==="choose")renderExerciseResults();
}
function renderScreen(key){return key==="welcome"?welcome():key==="goal"?goals():key==="experience"?experience():key==="schedule"?schedule():key==="units"?units():key==="profile"?profile():key==="body-composition"?bodyComposition():key==="priorities"?priorities():key==="preferences"?preferences():key==="nutrition-choice"?nutritionChoice():key==="nutrition-activity"?nutritionActivity():key==="nutrition-goal"?nutritionGoal():key==="nutrition-mode"?nutritionMode():key==="appearance"?appearance():acquisition()}
function welcome(){return `<section class="onboarding-screen onboarding-welcome"><div class="onboarding-brand-lockup"><img src="assets/level-up-mark-transparent.svg?v=1" alt=""><span>LEVEL UP</span></div><div class="onboarding-screen-intro"><span class="eyebrow">TRAINING · NUTRITION · RECOVERY</span><h1>Everything you need to level up.</h1><p>Your training, nutrition and recovery—working together in one personalized plan.</p></div>${progressPreview()}<div class="onboarding-feature-strip"><span><i>✓</i>Personalized training</span><span><i>✓</i>Meaningful progress</span><span><i>✓</i>Smarter recovery</span></div><div class="onboarding-welcome-actions"><button class="primary-btn" type="button" data-onboarding-start>${manualLaunch?"Review My Setup":"Build My Plan"}</button><button class="secondary-btn" type="button" data-onboarding-skip>Explore First</button></div></section>`}
function progressPreview(){return `<div class="onboarding-progress-preview" aria-label="Example Level Up progress. Preview data only."><div class="onboarding-preview-head"><div><span>EXAMPLE PROGRESS</span><strong>Momentum is building</strong></div><b>12 WEEKS</b></div><div class="onboarding-preview-grid"><article><div class="onboarding-preview-label"><span>Estimated 1RM</span><strong>+16%</strong></div><b>215 <small>lb</small></b><svg viewBox="0 0 164 66" role="img" aria-label="Example estimated one rep max increasing"><path class="preview-gridline" d="M2 54H162M2 32H162M2 10H162"/><path class="preview-area" d="M3 53 C25 52 34 48 51 47 S81 37 98 38 S126 27 161 13 L161 64 L3 64Z"/><path class="preview-line" pathLength="1" d="M3 53 C25 52 34 48 51 47 S81 37 98 38 S126 27 161 13"/><circle cx="161" cy="13" r="4"/></svg></article><article><div class="onboarding-preview-label"><span>Weight trend</span><strong>On track</strong></div><b>181.4 <small>lb</small></b><svg viewBox="0 0 164 66" role="img" aria-label="Example body-weight trend"><path class="preview-gridline" d="M2 54H162M2 32H162M2 10H162"/><path class="preview-daily" d="M3 51 L19 42 L35 47 L51 34 L67 38 L83 30 L99 34 L115 22 L131 27 L147 17 L161 20"/><path class="preview-trend" pathLength="1" d="M3 48 C36 44 55 40 82 34 S127 24 161 19"/><circle cx="161" cy="19" r="4"/></svg></article></div><p>Preview data shows how Level Up turns workouts and weigh-ins into useful trends.</p></div>`}
function intro(eyebrow,title,copy){return `<div class="onboarding-screen-intro"><span class="eyebrow">${eyebrow}</span><h2>${title}</h2><p>${copy}</p></div>`}
function goals(){return `<section class="onboarding-screen onboarding-goal-screen">${intro("START WITH THE OUTCOME","What do you want Level Up to help you achieve?","Your answer shapes training emphasis and your starting nutrition strategy.")}<div class="onboarding-goal-grid">${PRIMARY_GOALS.map(([v,l,d])=>`<button class="onboarding-goal-card ${answers.primaryGoal===v?"selected":""}" type="button" data-choice-group="goal" data-choice-value="${v}">${goalIcon(v)}<span><strong>${l}</strong><small>${d}</small></span><i>✓</i></button>`).join("")}</div></section>`}
function goalIcon(v){const p={build_muscle:'<path d="M4 9v6M7 7v10M17 7v10M20 9v6M7 12h10"/>',lose_fat_maintain_muscle:'<path d="M5 7h14M7 7l1 12h8l1-12M9 11h6M10 15h4"/>',maintain_muscle:'<path d="M4 12h5l2-5 3 10 2-5h4M7 20h10"/>',build_strength:'<path d="M4 9v6M7 7v10M17 7v10M20 9v6M7 12h10"/>',track_training:'<path d="M5 19V9M10 19V5M15 19v-7M20 19V3"/>'};return `<span class="onboarding-goal-icon"><svg viewBox="0 0 24 24">${p[v]}</svg></span>`}
function experience(){return `<section class="onboarding-screen onboarding-experience-screen">${intro("MATCH YOUR EXPERIENCE","Where are you in your training journey?","Level Up adjusts complexity, exercise selection and guidance to meet you where you are.")}<div class="onboarding-level-track"><span></span><i></i><i></i><i></i><i></i></div><div class="onboarding-experience-list">${EXPERIENCES.map(([v,l,d,e],i)=>`<button class="onboarding-experience-card ${answers.experience===v?"selected":""}" type="button" data-choice-group="experience" data-choice-value="${v}"><b>${String(i+1).padStart(2,"0")}</b><span><strong>${l}</strong><small>${d}</small><em>${e}</em></span><i>✓</i></button>`).join("")}</div></section>`}
function schedule(){return `<section class="onboarding-screen onboarding-schedule-screen">${intro("BUILD AROUND YOUR LIFE","What can you realistically sustain?","Your program will fit your schedule and the equipment you can reliably use.")}<div class="onboarding-week-preview"><div><span>Your training week</span><strong>${answers.days} sessions · ${answers.duration===90?"90+":answers.duration} min</strong></div><div class="onboarding-week-dots" role="group" aria-label="Choose training days">${WEEKDAY_ORDER.map(day=>`<button type="button" class="${answers.trainingDays.includes(day)?"active":""}" data-training-day="${day}" aria-pressed="${answers.trainingDays.includes(day)}" aria-label="${WEEKDAYS[day][1]}">${WEEKDAYS[day][0]}</button>`).join("")}</div><p>Tap the exact days you want to train. These will become your weekly workout schedule.</p></div><h3>Days per week</h3><div class="onboarding-number-row">${[2,3,4,5,6].map(v=>`<button class="onboarding-chip ${answers.days===v?"selected":""}" type="button" data-days="${v}">${v}</button>`).join("")}</div><h3>Typical workout length</h3><div class="onboarding-chip-grid onboarding-duration-grid">${[30,45,60,75,90].map(v=>`<button class="onboarding-chip ${answers.duration===v?"selected":""}" type="button" data-duration="${v}">${v===90?"90+":v}<small>min</small></button>`).join("")}</div><h3>Where do you train?</h3><div class="onboarding-setup-grid">${TRAINING_SETUPS.map(([v,l,d])=>`<button class="onboarding-setup-card ${answers.trainingSetup===v?"selected":""}" type="button" data-training-setup="${v}">${trainingSetupIcon(v)}<strong>${l}</strong><small>${d}</small><i>✓</i></button>`).join("")}</div></section>`}
function trainingSetupIcon(value){const paths={full_gym:'<path d="M4 21V5h16v16M8 9h2m4 0h2M8 13h2m4 0h2M8 17h2m4 0h2M10 21v-4h4v4M2 21h20"/>',home_gym:'<path d="M3 11 12 3l9 8v10H3ZM8 15v4m8-4v4M6 17h12M7 15v4m10-4v4"/>',minimal:'<path d="M3 9v6m3-8v10m12-10v10m3-8v6M6 12h12"/>',bodyweight:'<circle cx="12" cy="5" r="2.5"/><path d="M12 8v6m0-3-5 3m5-3 5 3m-5 0-4 7m4-7 4 7"/>'};return `<span class="onboarding-setup-icon" aria-hidden="true"><svg viewBox="0 0 24 24">${paths[value]}</svg></span>`}
function units(){return `<section class="onboarding-screen onboarding-units-screen">${intro("SET YOUR UNITS","How do you measure your progress?","Choose each unit separately. Your selections control how values are entered and displayed throughout Level Up.")}<div class="onboarding-unit-preferences" data-unit-text-ignore>${unitChoice("bodyWeight","Body weight",[["lb","lb"],["kg","kg"]])}${unitChoice("liftingWeight","Workout weights",[["lb","lb"],["kg","kg"]])}${unitChoice("distance","Cardio distance",[["km","Kilometres"],["mi","Miles"]])}${unitChoice("length","Height & measurements",[["cm","cm"],["in","ft / in"]])}</div><p class="onboarding-safety-note"><strong>You can mix units.</strong> For example, use pounds for body weight and kilometres for cardio. You can change these anytime in More → Units.</p></section>`}
function profile(){
 const u=answers.unitPreferences,mh=u.length==="cm",mw=u.bodyWeight==="kg";
 return `<section class="onboarding-screen onboarding-profile-screen">${intro("PERSONAL STARTING POINT","A few details to make it yours.","These details help calculate starting targets and select the right anatomy. Everything remains editable later.")}<div class="onboarding-profile-note"><span>⌁</span><p><strong>Private by design</strong>Your details are never shown publicly.</p></div><div class="onboarding-profile-grid"><label class="onboarding-profile-wide">What should we call you? <small>(optional)</small><input data-answer="displayName" type="text" autocomplete="nickname" maxlength="40" value="${esc(answers.displayName)}" placeholder="Name or username"></label><label>Age<input data-answer="age" type="number" inputmode="numeric" min="18" max="100" value="${esc(answers.age)}" placeholder="Age"></label><label>Anatomy<select data-answer="sex"><option value="">Choose</option><option value="male" ${answers.sex==="male"?"selected":""}>Male</option><option value="female" ${answers.sex==="female"?"selected":""}>Female</option></select></label>${mh?`<label class="onboarding-profile-wide">Height (cm)<input data-unit-input-ignore data-answer="heightCm" type="number" inputmode="decimal" min="90" max="250" step=".1" value="${esc(answers.heightCm)}" placeholder="Height"></label>`:`<label>Height (ft)<input data-unit-input-ignore data-answer="heightFeet" type="number" inputmode="numeric" min="3" max="8" value="${esc(answers.heightFeet)}" placeholder="5"></label><label>Height (in)<input data-unit-input-ignore data-answer="heightInches" type="number" inputmode="decimal" min="0" max="11" step=".1" value="${esc(answers.heightInches)}" placeholder="10"></label>`}${mw?`<label class="onboarding-profile-wide">Weight (kg)<input data-unit-input-ignore data-answer="weightKg" type="number" inputmode="decimal" min="1" step=".1" value="${esc(answers.weightKg)}" placeholder="Weight"></label>`:`<label class="onboarding-profile-wide">Weight (lb)<input data-unit-input-ignore data-answer="weightLb" type="number" inputmode="decimal" min="1" step=".1" value="${esc(answers.weightLb)}" placeholder="Weight"></label>`}</div></section>`;
}
function bodyComposition(){return `<section class="onboarding-screen onboarding-body-composition-screen" data-anatomy-sex="${answers.sex === "female" ? "female" : "male"}">${intro("BODY COMPOSITION · OPTIONAL","Which body-composition range looks closest to you?","Choose the closest visual estimate, or select Not sure. This is optional and is not a medical assessment.")}<div data-body-composition-slot></div></section>`}
function priorities(){return `<section class="onboarding-screen onboarding-priority-screen">${intro("CHOOSE YOUR FOCUS","What do you especially want to improve?","Tap up to three areas. Level Up will emphasize them while keeping your program balanced.")}<div class="onboarding-priority-status"><strong>${answers.priorities.length?`${answers.priorities.length} selected`:"Balanced development"}</strong><span>${answers.priorities.length?answers.priorities.join(" · "):"No priority muscles selected"}</span></div><div class="muscle-priority-grid">${MUSCLES.map(m=>renderMusclePriorityChoice(m,answers.priorities.includes(m))).join("")}</div><button class="onboarding-no-priority ${answers.priorities.length===0?"selected":""}" type="button" data-no-priority>No particular priority</button></section>`}
function preferences(){return `<section class="onboarding-screen onboarding-preference-screen">${intro("TRAIN YOUR WAY","Anything you would prefer to avoid?","Level Up can swap exercises while preserving the purpose of your program.")}<div class="onboarding-swap-preview"><span><small>PROGRAMMED</small><strong>Barbell squat</strong></span><i>→</i><span><small>SMART SWAP</small><strong>Leg press</strong></span></div><div class="onboarding-option-stack onboarding-limit-options">${choice("limitations","none","No preferences or limitations",answers.limitationMode==="none","Use the best-matched exercises.")}${choice("limitations","choose","Choose exercises to avoid",answers.limitationMode==="choose","Search your exercise library.")}</div>${answers.limitationMode==="choose"?`<div class="onboarding-exercise-picker"><input id="onboarding-exercise-search" type="search" value="${esc(answers.exerciseSearch)}" placeholder="Search exercise, muscle or equipment"><div class="onboarding-selected-exercises">${selectedExercises()}</div><div id="onboarding-exercise-results" class="onboarding-exercise-results"></div></div>`:""}<p class="onboarding-safety-note">Exercise preferences are not a medical screening. Stop if an exercise causes pain.</p></section>`}
function nutritionChoice(){return `<section class="onboarding-screen onboarding-nutrition-choice-screen">${intro("PERSONALIZE YOUR APP","Do you want to track nutrition?","If you choose yes, Level Up will ask a few nutrition questions and set up food logging, calorie targets and nutrition progress. You can change this anytime in More → Nutrition Tracking.")}<div class="onboarding-option-stack" role="radiogroup" aria-label="Track nutrition">${choice("trackNutrition","yes","Yes, track my nutrition",answers.trackNutrition===true,"Set up calories, macros and food logging.")}${choice("trackNutrition","no","No, focus on training",answers.trackNutrition===false,"Hide nutrition features without removing them permanently.")}</div><p class="onboarding-safety-note"><strong>Your choice is reversible.</strong> Turning nutrition off never deletes saved nutrition data.</p></section>`}
function nutritionActivity(){return `<section class="onboarding-screen">${intro("ENERGY NEEDS","How active is your typical week?","This helps Level Up estimate your maintenance calories.")}<div class="onboarding-option-stack">${Object.entries(ACTIVITY_LEVELS).map(([id,item])=>`<button class="onboarding-option ${answers.nutritionActivity===id?"selected":""}" type="button" data-nutrition-activity="${esc(id)}"><strong>${esc(item.label)}</strong><small>${esc(item.description)}</small><i>✓</i></button>`).join("")}</div></section>`}
function nutritionGoal(){const plan=nutritionPreview();return `<section class="onboarding-screen">${intro("NUTRITION PHASE","What should your calories support right now?","Choose the direction you want your weight to move. Level Up uses your estimated maintenance and goal to create a starting calorie target.")}<div class="onboarding-option-stack">${Object.entries(GOAL_PRESETS).map(([id,item])=>`<button class="onboarding-option ${answers.nutritionGoalId===id?"selected":""}" type="button" data-nutrition-goal="${esc(id)}"><strong>${esc(item.label)}</strong><small>${esc(item.description)}</small><i>✓</i></button>`).join("")}</div><div data-nutrition-preview>${plan?nutritionPreviewMarkup(plan):""}</div></section>`}
function nutritionPreview(){const profile=nutritionProfileFromAnswers(),goal=GOAL_PRESETS[answers.nutritionGoalId];if(!profile||!ACTIVITY_LEVELS[answers.nutritionActivity]||!goal)return null;try{const maintenance=Math.round(Number(calculateTdee({...profile,activity:answers.nutritionActivity}).tdee));if(!Number.isFinite(maintenance)||maintenance<=0)return null;return{maintenance,adjustment:Number(goal.dailyCalorieAdjustment||0),target:Math.round(maintenance+Number(goal.dailyCalorieAdjustment||0))}}catch{return null}}
function nutritionPreviewMarkup(plan){const sign=plan.adjustment>0?"+":plan.adjustment<0?"−":"",absolute=Math.abs(plan.adjustment),equation=plan.adjustment===0?`${plan.maintenance.toLocaleString()} maintenance = ${plan.target.toLocaleString()} target`:`${plan.maintenance.toLocaleString()} ${sign} ${absolute.toLocaleString()} = ${plan.target.toLocaleString()} target`;return `<div class="onboarding-nutrition-preview"><div><span>Estimated maintenance</span><strong>${plan.maintenance.toLocaleString()} kcal/day</strong></div><div><span>Goal adjustment</span><strong>${sign}${absolute.toLocaleString()} kcal/day</strong></div><div><span>Starting calorie target</span><strong>${plan.target.toLocaleString()} kcal/day</strong></div><p class="onboarding-nutrition-equation"><strong>${equation}</strong><span>Maintenance is the starting point used to calculate your target.</span></p></div>`}
function nutritionMode(){return `<section class="onboarding-screen onboarding-nutrition-mode-screen">${intro("NUTRITION MODE","How should Level Up handle your calories?","You can change this later in Nutrition → Goals & Plan.")}<div data-nutrition-mode-content>${nutritionModeContent()}</div></section>`}
function nutritionModeContent(){const coach=answers.nutritionMode==="coach",plan=nutritionPreview();return `<div class="onboarding-nutrition-mode-cards" role="radiogroup" aria-label="Nutrition mode"><button type="button" class="onboarding-nutrition-mode-card ${coach?"selected":""}" data-nutrition-program="coach" role="radio" aria-checked="${coach}"><em>RECOMMENDED</em><strong>Level Up Coach</strong><small>Review your target using completed food logs and Trend Weight.</small></button><button type="button" class="onboarding-nutrition-mode-card ${!coach?"selected":""}" data-nutrition-program="manual" role="radio" aria-checked="${!coach}"><strong>Track Manually</strong><small>You control the calorie target while food logging and analytics stay on.</small></button></div>${coach?`<div class="onboarding-coach-update-choice"><span>WHEN A WEEKLY UPDATE IS READY</span><div role="radiogroup" aria-label="Coach update preference"><button type="button" class="${answers.coachUpdateMode==="review"?"selected":""}" data-nutrition-coach-update="review" aria-pressed="${answers.coachUpdateMode==="review"}">Review before applying</button><button type="button" class="${answers.coachUpdateMode==="automatic"?"selected":""}" data-nutrition-coach-update="automatic" aria-pressed="${answers.coachUpdateMode==="automatic"}">Apply automatically</button></div><small>First review: Day 14. Later reviews require enough nutrition and weight data.</small></div>`:`<div class="onboarding-manual-mode-note"><strong>${plan?`${plan.target.toLocaleString()} kcal/day starting target`:"Manual tracking"}</strong><span>Level Up will not change this target automatically.</span></div>`}`}
function appearance(){
 const themes=answers.showAllThemes?APPEARANCE_THEMES:APPEARANCE_THEMES.filter(t=>FEATURED_THEMES.includes(t.id));
 return `<section class="onboarding-screen onboarding-appearance-screen">${intro("MAKE LEVEL UP YOURS","Choose your appearance.","Each preview is live. Your choice applies throughout the app and can be changed anytime.")}<div class="onboarding-theme-grid" role="radiogroup" aria-label="App appearance">${themes.map(themeCard).join("")}</div>${answers.showAllThemes?"":'<button class="onboarding-show-themes" type="button" data-show-themes>See all appearances</button>'}<div class="onboarding-ready-preview"><span>✓</span><p><strong>Ready for your plan</strong>Your goal, schedule, equipment and preferences are set.</p></div></section>`;
}
function acquisition(){return `<section class="onboarding-screen onboarding-acquisition-screen">${intro("ONE LAST QUESTION","How did you find us?","This helps us understand what is working.")}<div class="onboarding-acquisition-list" role="radiogroup" aria-label="How did you find Level Up?">${ACQUISITION_SOURCES.map(([v,l])=>{const selected=answers.acquisitionSource===v;return `<button class="onboarding-acquisition-choice ${selected?"selected":""}" type="button" role="radio" aria-checked="${selected}" data-choice-group="acquisition" data-choice-value="${v}"><span class="onboarding-acquisition-icon acquisition-icon-${v}" aria-hidden="true">${acquisitionIcon(v)}</span><strong>${l}</strong><span class="onboarding-acquisition-check" aria-hidden="true">✓</span></button>`}).join("")}</div></section>`}
function acquisitionIcon(value){const icons={
 app_recommendation:'<svg viewBox="0 0 44 44"><defs><linearGradient id="app-store-gradient" x1="8" y1="4" x2="36" y2="40" gradientUnits="userSpaceOnUse"><stop stop-color="#35C9FF"/><stop offset="1" stop-color="#0878EE"/></linearGradient></defs><rect width="44" height="44" rx="11" fill="url(#app-store-gradient)"/><path d="M14.5 31.5 22 18.4m0 0 3.1-5.4m-3.1 5.4 7.6 13.1M10.5 27h23" fill="none" stroke="#fff" stroke-width="3.2" stroke-linecap="round"/></svg>',
 google_search:'<svg viewBox="0 0 44 44"><path fill="#4285F4" d="M38.1 22.4c0-1.2-.1-2.4-.3-3.5H22v6.5h9.1a7.8 7.8 0 0 1-3.4 5.1v4.3h5.5c3.2-3 4.9-7.3 4.9-12.4Z"/><path fill="#34A853" d="M22 38.8c4.6 0 8.4-1.5 11.2-4.1l-5.5-4.3c-1.5 1-3.5 1.7-5.7 1.7-4.4 0-8.2-3-9.5-7.1H6.8v4.4A16.9 16.9 0 0 0 22 38.8Z"/><path fill="#FBBC05" d="M12.5 25a10.3 10.3 0 0 1 0-6.5v-4.4H6.8a16.9 16.9 0 0 0 0 15.3l5.7-4.4Z"/><path fill="#EA4335" d="M22 11.4c2.5 0 4.8.9 6.6 2.6l4.8-4.8A16.2 16.2 0 0 0 22 4.7a16.9 16.9 0 0 0-15.2 9.4l5.7 4.4c1.3-4.1 5.1-7.1 9.5-7.1Z"/></svg>',
 instagram:'<svg viewBox="0 0 44 44"><defs><radialGradient id="instagram-gradient" cx="13" cy="39" r="43" gradientUnits="userSpaceOnUse"><stop stop-color="#FFD600"/><stop offset=".45" stop-color="#FF3A6D"/><stop offset="1" stop-color="#833AB4"/></radialGradient></defs><rect x="3" y="3" width="38" height="38" rx="11" fill="url(#instagram-gradient)"/><rect x="10.5" y="10.5" width="23" height="23" rx="7" fill="none" stroke="#fff" stroke-width="3"/><circle cx="22" cy="22" r="5.8" fill="none" stroke="#fff" stroke-width="3"/><circle cx="30.4" cy="13.8" r="1.8" fill="#fff"/></svg>',
 tiktok:'<svg viewBox="0 0 44 44"><circle cx="22" cy="22" r="22" fill="#070707"/><path d="M25 10v16.5a6.8 6.8 0 1 1-5.7-6.7" fill="none" stroke="#25F4EE" stroke-width="4" stroke-linecap="round"/><path d="M27.5 10c.7 4.2 3 6.6 6.5 7.2M27.5 11.5V28a6.8 6.8 0 0 1-12.2 4.1" fill="none" stroke="#FE2C55" stroke-width="4" stroke-linecap="round"/><path d="M26.2 9.8v16.9a6.7 6.7 0 1 1-5.4-6.6M26.2 10c.7 4.2 3.1 6.7 6.7 7.3" fill="none" stroke="#fff" stroke-width="2.6" stroke-linecap="round"/></svg>',
 youtube:'<svg viewBox="0 0 44 44"><rect x="3" y="8" width="38" height="28" rx="8" fill="#FF0033"/><path d="m18.5 16.2 10.5 5.8-10.5 5.8Z" fill="#fff"/></svg>',
 reddit:'<svg viewBox="0 0 44 44"><circle cx="22" cy="22" r="22" fill="#FF4500"/><path d="M12.2 23.8c0 5 4.4 8.5 9.8 8.5s9.8-3.5 9.8-8.5c0-4.4-4.4-7.5-9.8-7.5s-9.8 3.1-9.8 7.5Z" fill="#fff"/><circle cx="17.5" cy="23.5" r="1.8" fill="#FF4500"/><circle cx="26.5" cy="23.5" r="1.8" fill="#FF4500"/><path d="M17.5 27.5c2.5 1.7 6.5 1.7 9 0M22 16.2l1.2-5.4 5.3 1.2" fill="none" stroke="#FF4500" stroke-width="1.6" stroke-linecap="round"/><circle cx="30.1" cy="12.3" r="2.4" fill="#fff" stroke="#FF4500" stroke-width="1.4"/><circle cx="10.7" cy="20.4" r="2.4" fill="#fff"/><circle cx="33.3" cy="20.4" r="2.4" fill="#fff"/></svg>',
 friend_family:'<svg viewBox="0 0 44 44"><circle cx="17" cy="17" r="5"/><circle cx="29" cy="18.5" r="4"/><path d="M7 34c.8-7 4.1-10.5 10-10.5S26.2 27 27 34M25 25c5.8 0 9.3 3 10 9"/></svg>',
 other:'<svg viewBox="0 0 44 44"><circle cx="22" cy="22" r="15" fill="none" stroke="currentColor" stroke-width="2.5"/><circle cx="15.5" cy="22" r="2.1"/><circle cx="22" cy="22" r="2.1"/><circle cx="28.5" cy="22" r="2.1"/></svg>'
};return icons[value]||icons.other}
function themeCard(t){const s=answers.theme===t.id,e=resolveAppearanceTheme(t.id);return `<button class="onboarding-theme-card theme-preview-${t.id}${s?" selected":""}" type="button" role="radio" aria-checked="${s}" data-onboarding-theme="${t.id}"><span class="onboarding-theme-check">✓</span><span class="appearance-theme-preview" data-preview-effective="${e}"><i class="appearance-preview-top"></i><i class="appearance-preview-card"><b></b><em></em><small></small></i><i class="appearance-preview-nav"></i></span><strong>${esc(t.name)}</strong><small>${esc(t.description)}</small></button>`}
function unitChoice(kind,label,options){return `<div class="onboarding-unit-row"><strong>${label}</strong><div role="radiogroup" aria-label="${label}">${options.map(([v,t])=>`<button type="button" data-unit-kind="${kind}" data-unit-value="${v}" class="${answers.unitPreferences[kind]===v?"selected":""}" aria-pressed="${answers.unitPreferences[kind]===v}">${t}</button>`).join("")}</div></div>`}
function choice(group,value,label,selected,detail=""){return `<button class="onboarding-option ${selected?"selected":""}" type="button" data-choice-group="${group}" data-choice-value="${esc(value)}"><strong>${esc(label)}</strong>${detail?`<small>${esc(detail)}</small>`:""}<i>✓</i></button>`}
function renderFooter(){const keys=screenKeys();if(step===0||step===keys.length)return"";return `<footer class="levelup-onboarding-footer"><button class="secondary-btn" type="button" data-onboarding-back>Back</button><button class="primary-btn" type="button" data-onboarding-next>${currentScreen()==="acquisition"?"Create My Plan":"Continue"}</button></footer>`}
function renderCompletion(){
 const goal=PRIMARY_GOALS.find(([v])=>v===answers.primaryGoal)?.[1]||"Personal progress",exp=EXPERIENCES.find(([v])=>v===answers.experience)?.[1]||"Personalized",setup=TRAINING_SETUPS.find(([v])=>v===answers.trainingSetup)?.[1]||"Your equipment",priority=answers.priorities.length?answers.priorities.join(" · "):"Balanced development",trainingDayNames=normalizeTrainingDays(answers.trainingDays).map(day=>WEEKDAYS[day][2]).join(" · ");
 const nutritionSummary=answers.trackNutrition?"Calories, macros and food logging are ready":"Hidden for now · turn on anytime in More";
 return `<section class="onboarding-screen onboarding-completion"><div class="onboarding-complete-hero"><span class="onboarding-complete-mark">✓</span><span class="eyebrow">BUILT AROUND YOU</span><h2>${answers.displayName?`${esc(answers.displayName)}, your`:"Your"} Level Up plan is ready.</h2><p>A clear starting point that can adapt as you log workouts, recovery${answers.trackNutrition?", nutrition":""} and progress.</p></div>${completionStorageWarning?'<div class="onboarding-storage-warning"><strong>Your plan is ready.</strong><span>Private browsing blocked some settings from being saved permanently.</span></div>':""}<div class="onboarding-build-sequence"><div><i>✓</i><span><strong>Training schedule</strong><small>${trainingDayNames} · ${answers.duration===90?"90+":answers.duration} minute sessions</small></span></div><div><i>✓</i><span><strong>Program direction</strong><small>${esc(goal)} · ${esc(exp)}</small></span></div><div><i>✓</i><span><strong>Equipment & focus</strong><small>${esc(setup)} · ${esc(priority)}</small></span></div><div><i>✓</i><span><strong>Nutrition</strong><small>${nutritionSummary}</small></span></div></div><div class="onboarding-plan-preview"><div class="onboarding-plan-preview-head"><span>YOUR STARTING POINT</span><b>PERSONALIZED</b></div><div class="onboarding-plan-metrics"><div><span>Training</span><strong>${answers.days}×</strong><small>per week</small></div><div><span>Focus</span><strong>${answers.priorities.length||"All"}</strong><small>${answers.priorities.length?"priority areas":"muscle groups"}</small></div><div><span>Progress</span><strong>Ready</strong><small>starts with your first log</small></div></div><div class="onboarding-empty-trend"><svg viewBox="0 0 300 68"><path d="M1 57H299M1 31H299M1 5H299"/><path class="empty-trend-path" d="M2 55 C48 52 74 46 105 42 S165 35 201 26 S255 18 298 7"/></svg><p><strong>Your progress starts here.</strong>Complete workouts and weigh-ins to build your personal trends.</p></div></div><div class="onboarding-completion-actions"><button class="primary-btn" type="button" data-onboarding-finish="smart">Build My Workout Program</button><button class="secondary-btn" type="button" data-onboarding-finish="templates">Choose a Template</button><button class="onboarding-text-action" type="button" data-onboarding-finish="home">Explore the App</button></div></section>`;
}
function handleClick(e){
 const b=e.target.closest("button");if(!b||!overlay?.contains(b))return;
 if(b.matches("[data-onboarding-skip]"))return skipOnboarding();
 if(b.matches("[data-onboarding-start]")){step=1;return render()}
 if(b.matches("[data-onboarding-back]")){step=Math.max(0,step-1);return render()}
 if(b.matches("[data-onboarding-next]")){if(!valid(currentScreen()))return;if(step===screenKeys().length-1)return complete();step++;return render()}
 if(b.matches("[data-show-themes]")){answers.showAllThemes=true;return render()}
 if(b.dataset.onboardingTheme){answers.theme=b.dataset.onboardingTheme;applyAppearanceTheme(answers.theme);syncThemeChoices();return updateContinueState()}
 if(b.dataset.unitKind&&b.dataset.unitValue){changeUnit(b.dataset.unitKind,b.dataset.unitValue);syncUnitChoices();return updateContinueState()}
 if(b.dataset.choiceGroup){const group=b.dataset.choiceGroup;applyChoice(group,b.dataset.choiceValue);if(group==="acquisition"||group==="goal"||group==="experience"){syncChoiceGroup(group,b.dataset.choiceValue);return updateContinueState()}if(group==="trackNutrition"){syncChoiceGroup(group,b.dataset.choiceValue);syncOnboardingProgress();return updateContinueState()}return render()}
 if(b.dataset.nutritionActivity){answers.nutritionActivity=b.dataset.nutritionActivity;syncNutritionSelection("[data-nutrition-activity]",b.dataset.nutritionActivity,"nutritionActivity");return updateContinueState()}
 if(b.dataset.nutritionGoal){answers.nutritionGoalId=b.dataset.nutritionGoal;syncNutritionSelection("[data-nutrition-goal]",b.dataset.nutritionGoal,"nutritionGoal");const host=overlay?.querySelector("[data-nutrition-preview]");const plan=nutritionPreview();if(host)host.innerHTML=plan?nutritionPreviewMarkup(plan):"";return updateContinueState()}
 if(b.dataset.nutritionProgram){answers.nutritionMode=b.dataset.nutritionProgram;const host=overlay?.querySelector("[data-nutrition-mode-content]");if(host)host.innerHTML=nutritionModeContent();return updateContinueState()}
 if(b.dataset.nutritionCoachUpdate){answers.coachUpdateMode=b.dataset.nutritionCoachUpdate;syncNutritionSelection("[data-nutrition-coach-update]",b.dataset.nutritionCoachUpdate,"nutritionCoachUpdate");return updateContinueState()}
 if(b.dataset.trainingSetup){const x=TRAINING_SETUPS.find(([v])=>v===b.dataset.trainingSetup);if(x){answers.trainingSetup=x[0];answers.equipment=[...x[3]]}syncScheduleScreen();return updateContinueState()}
 if(b.dataset.priority){togglePriority(b.dataset.priority);syncPriorityScreen();return updateContinueState()}
 if(b.matches("[data-no-priority]")){answers.priorities=[];syncPriorityScreen();return updateContinueState()}
 if(b.dataset.trainingDay!==undefined){toggleTrainingDay(Number(b.dataset.trainingDay));syncScheduleScreen();return updateContinueState()}
 if(b.dataset.days){answers.days=Number(b.dataset.days);answers.trainingDays=defaultTrainingDays(answers.days);syncScheduleScreen();return updateContinueState()}
 if(b.dataset.duration){answers.duration=Number(b.dataset.duration);syncScheduleScreen();return updateContinueState()}
 if(b.dataset.avoidAdd){if(!answers.excludedIds.includes(b.dataset.avoidAdd))answers.excludedIds.push(b.dataset.avoidAdd);return render()}
 if(b.dataset.avoidRemove){answers.excludedIds=answers.excludedIds.filter(id=>id!==b.dataset.avoidRemove);return render()}
 if(b.dataset.onboardingFinish)finishRoute(b.dataset.onboardingFinish);
}
function handleInput(e){const f=e.target;if(f.dataset?.answer)answers[f.dataset.answer]=f.value;if(f.dataset?.answer==="sex"){window.__levelUpAnatomySexPreview=answers.sex;window.dispatchEvent(new CustomEvent("levelup:profile-updated"))}if(f.id==="onboarding-exercise-search"){answers.exerciseSearch=f.value;renderExerciseResults()}updateContinueState()}
function changeUnit(kind,v){const ok={bodyWeight:["lb","kg"],liftingWeight:["lb","kg"],distance:["km","mi"],length:["cm","in"]};if(!ok[kind]?.includes(v))return;if(kind==="length"&&v==="cm"){const n=Number(answers.heightFeet)*12+Number(answers.heightInches);if(n>0)answers.heightCm=String(Math.round(inchesToCentimeters(n)*10)/10)}if(kind==="length"&&v==="in"){const cm=Number(answers.heightCm);if(cm>0){const n=centimetersToInches(cm);answers.heightFeet=String(Math.floor(n/12));answers.heightInches=String(Math.round(n%12*10)/10)}}if(kind==="bodyWeight"&&v==="kg"&&Number(answers.weightLb)>0)answers.weightKg=String(Math.round(poundsToKilograms(Number(answers.weightLb))*10)/10);if(kind==="bodyWeight"&&v==="lb"&&Number(answers.weightKg)>0)answers.weightLb=String(Math.round(kilogramsToPounds(Number(answers.weightKg))*10)/10);answers.unitPreferences={...answers.unitPreferences,[kind]:v}}
function applyChoice(g,v){if(g==="goal"){answers.primaryGoal=v;if(!answers.nutritionGoalId)answers.nutritionGoalId=suggestNutritionGoal(v)}if(g==="experience")answers.experience=v;if(g==="limitations"){answers.limitationMode=v;if(v==="none")answers.excludedIds=[]}if(g==="trackNutrition")answers.trackNutrition=v==="yes";if(g==="acquisition"){answers.acquisitionSource=v;if(v!=="other")answers.acquisitionOther=""}}
function togglePriority(m){answers.priorities=answers.priorities.includes(m)?answers.priorities.filter(x=>x!==m):answers.priorities.length<3?[...answers.priorities,m]:answers.priorities}
function toggleTrainingDay(day){const selected=normalizeTrainingDays(answers.trainingDays);if(selected.includes(day)){if(selected.length<=2)return;answers.trainingDays=selected.filter(value=>value!==day)}else{if(selected.length>=6)return;answers.trainingDays=normalizeTrainingDays([...selected,day])}answers.days=answers.trainingDays.length}
function syncChoiceGroup(group,value){overlay?.querySelectorAll(`[data-choice-group="${group}"]`).forEach(button=>{const selected=button.dataset.choiceValue===value;button.classList.toggle("selected",selected);button.setAttribute(button.getAttribute("role")==="radio"?"aria-checked":"aria-pressed",String(selected))})}
function syncNutritionSelection(selector,value,datasetKey){overlay?.querySelectorAll(selector).forEach(button=>{const selected=button.dataset[datasetKey]===value;button.classList.toggle("selected",selected);button.setAttribute(button.getAttribute("role")==="radio"?"aria-checked":"aria-pressed",String(selected))})}
function syncOnboardingProgress(){const keys=screenKeys(),total=keys.length-1,pos=Math.max(1,step),counter=overlay?.querySelector(".levelup-onboarding-topbar strong"),bar=overlay?.querySelector(".levelup-onboarding-progress span");if(counter)counter.textContent=`${pos} of ${total}`;if(bar)bar.style.width=`${pos/total*100}%`}
function syncThemeChoices(){overlay?.querySelectorAll("[data-onboarding-theme]").forEach(button=>{const selected=button.dataset.onboardingTheme===answers.theme;button.classList.toggle("selected",selected);button.setAttribute("aria-checked",String(selected))})}
function syncUnitChoices(){overlay?.querySelectorAll("[data-unit-kind]").forEach(button=>{const selected=answers.unitPreferences[button.dataset.unitKind]===button.dataset.unitValue;button.classList.toggle("selected",selected);button.setAttribute("aria-pressed",String(selected))})}
function syncScheduleScreen(){const screen=overlay?.querySelector(".onboarding-schedule-screen");if(!screen)return;const summary=screen.querySelector(".onboarding-week-preview>div:first-child strong");if(summary)summary.textContent=`${answers.days} sessions · ${answers.duration===90?"90+":answers.duration} min`;screen.querySelectorAll("[data-training-day]").forEach(button=>{const selected=answers.trainingDays.includes(Number(button.dataset.trainingDay));button.classList.toggle("active",selected);button.setAttribute("aria-pressed",String(selected))});screen.querySelectorAll("[data-days]").forEach(button=>button.classList.toggle("selected",Number(button.dataset.days)===answers.days));screen.querySelectorAll("[data-duration]").forEach(button=>button.classList.toggle("selected",Number(button.dataset.duration)===answers.duration));screen.querySelectorAll("[data-training-setup]").forEach(button=>{const selected=button.dataset.trainingSetup===answers.trainingSetup;button.classList.toggle("selected",selected);button.setAttribute("aria-pressed",String(selected))})}
function syncPriorityScreen(){const screen=overlay?.querySelector(".onboarding-priority-screen");if(!screen)return;screen.querySelectorAll("[data-priority]").forEach(button=>{const selected=answers.priorities.includes(button.dataset.priority);button.classList.toggle("selected",selected);button.setAttribute("aria-pressed",String(selected))});screen.querySelector("[data-no-priority]")?.classList.toggle("selected",answers.priorities.length===0);const strong=screen.querySelector(".onboarding-priority-status strong"),summary=screen.querySelector(".onboarding-priority-status span");if(strong)strong.textContent=answers.priorities.length?`${answers.priorities.length} selected`:"Balanced development";if(summary)summary.textContent=answers.priorities.length?answers.priorities.join(" · "):"No priority muscles selected"}
function valid(key){if(key==="goal")return!!answers.primaryGoal;if(key==="experience")return!!answers.experience;if(key==="schedule")return[2,3,4,5,6].includes(Number(answers.days))&&[30,45,60,75,90].includes(Number(answers.duration))&&TRAINING_SETUPS.some(([v])=>v===answers.trainingSetup);if(key==="profile"){const age=Number(answers.age),mh=answers.unitPreferences.length==="cm",mw=answers.unitPreferences.bodyWeight==="kg",ft=Number(answers.heightFeet),inch=Number(answers.heightInches),cm=Number(answers.heightCm),w=Number(mw?answers.weightKg:answers.weightLb),height=mh?cm>=90&&cm<=250:ft>=3&&ft<=8&&inch>=0&&inch<=11;return age>=18&&age<=100&&["male","female"].includes(answers.sex)&&height&&w>0}if(key==="nutrition-choice")return typeof answers.trackNutrition==="boolean";if(key==="nutrition-activity")return Boolean(ACTIVITY_LEVELS[answers.nutritionActivity]);if(key==="nutrition-goal")return Boolean(GOAL_PRESETS[answers.nutritionGoalId]&&nutritionPreview());if(key==="nutrition-mode")return answers.nutritionMode==="manual"||answers.nutritionMode==="coach";if(key==="appearance")return APPEARANCE_THEMES.some(t=>t.id===answers.theme);if(key==="acquisition")return ACQUISITION_SOURCES.some(([source])=>source===answers.acquisitionSource);return true}
function updateContinueState(){const b=overlay?.querySelector("[data-onboarding-next]");if(b)b.disabled=!valid(currentScreen())}
function complete(){
 const age=Number(answers.age),mh=answers.unitPreferences.length==="cm",mw=answers.unitPreferences.bodyWeight==="kg",heightCm=mh?Number(answers.heightCm):feetAndInchesToCm(Number(answers.heightFeet),Number(answers.heightInches)),ti=centimetersToInches(heightCm),feet=mh?Math.floor(ti/12):Number(answers.heightFeet),inches=mh?Number((ti-feet*12).toFixed(1)):Number(answers.heightInches),weightLb=mw?kilogramsToPounds(Number(answers.weightKg)):Number(answers.weightLb),weightKg=poundsToKg(weightLb);let failed=false;const attempt=fn=>{try{fn()}catch(err){failed=true;console.warn("Level Up onboarding storage write failed",err)}};
 attempt(()=>saveNutritionProfile({...getNutritionProfile(),displayName:String(answers.displayName||"").trim().slice(0,40),age,sex:answers.sex,heightFeet:feet,heightInches:inches,weightLb,heightCm,weightKg}));attempt(()=>setUnitPreferences(answers.unitPreferences));attempt(()=>saveInitialWeight(weightLb));attempt(()=>saveTrainingPreferences({primaryGoal:answers.primaryGoal,experience:answers.experience,priorities:answers.priorities,days:Number(answers.days),duration:Number(answers.duration),trainingDays:answers.trainingDays,trainingSetup:answers.trainingSetup,equipment:answers.equipment,excludedIds:answers.limitationMode==="choose"?answers.excludedIds:[],nutritionEnabled:answers.trackNutrition===true}));attempt(()=>saveNutritionOnboarding());attempt(()=>markOnboardingComplete({migrated:false}));attempt(()=>setNutritionEnabled(answers.trackNutrition===true));
 if(answers.acquisitionSource)void saveReportedSource(answers.acquisitionSource,answers.acquisitionOther);void trackProductEvent("onboarding_completed",{eventKey:"onboarding-v2",metadata:{primaryGoal:answers.primaryGoal,experience:answers.experience,days:Number(answers.days),trainingSetup:answers.trainingSetup,nutritionEnabled:answers.trackNutrition===true}});completionStorageWarning=failed;window.dispatchEvent(new CustomEvent("levelup:nutrition-updated"));step=screenKeys().length;render();
}
function nutritionProfileFromAnswers(){const mh=answers.unitPreferences.length==="cm",mw=answers.unitPreferences.bodyWeight==="kg",heightCm=mh?Number(answers.heightCm):feetAndInchesToCm(Number(answers.heightFeet),Number(answers.heightInches)),weightLb=mw?kilogramsToPounds(Number(answers.weightKg)):Number(answers.weightLb);return{...getNutritionProfile(),age:Number(answers.age),sex:answers.sex,heightCm,weightLb,weightKg:poundsToKg(weightLb)}}
function saveNutritionOnboarding(){
 const handledAt=new Date().toISOString();
 if(answers.trackNutrition!==true){saveTrainingPreferences({nutritionSetupComplete:false,nutritionSetupSkipped:true,nutritionSetupHandledAt:handledAt});return}
 const plan=nutritionPreview(),goalId=answers.nutritionGoalId;if(!plan||!GOAL_PRESETS[goalId])throw new Error("Nutrition onboarding is incomplete");
 saveNutritionProfile({...nutritionProfileFromAnswers(),activity:answers.nutritionActivity});
 localStorage.removeItem("level_up_manual_maintenance_calories");
 saveNutritionPhase({goalId,maintenanceCalories:plan.maintenance,targetCalories:plan.target});
 saveNutritionGoal({goalId,updatedAt:handledAt,source:"onboarding-nutrition"});
 syncCalculatedCalories(plan.target);
 if(answers.nutritionMode==="manual"){localStorage.setItem(MANUAL_TARGET_KEY,String(plan.target));setMaintenanceUpdateMode("track")}else setMaintenanceUpdateMode(answers.coachUpdateMode==="automatic"?"automatic":"review");
 saveTrainingPreferences({nutritionSetupComplete:true,nutritionSetupSkipped:false,nutritionSetupHandledAt:handledAt});
 window.dispatchEvent(new CustomEvent("levelup:nutrition-mode-updated",{detail:{mode:answers.nutritionMode,updateMode:getMaintenanceUpdateMode()}}));window.dispatchEvent(new CustomEvent("levelup:nutrition-phase-updated"));
}
function suggestNutritionGoal(goal){if(goal==="build_muscle")return"bulk_conservative";if(goal==="lose_fat_maintain_muscle")return"cut_gentle";if(goal==="maintain_muscle")return"maintain";return""}
function saveInitialWeight(weight){const entries=readJson(WEIGHT_KEY);if(Array.isArray(entries)&&entries.length)return;const n=new Date(),date=`${n.getFullYear()}-${String(n.getMonth()+1).padStart(2,"0")}-${String(n.getDate()).padStart(2,"0")}`;localStorage.setItem(WEIGHT_KEY,JSON.stringify([{date,weight:Math.round(Number(weight)*10)/10}]))}
function skipOnboarding(){let prefs={};try{prefs=getTrainingPreferences()}catch{}if(!prefs.onboardingComplete)try{markOnboardingSkipped()}catch{}closeOnboarding()}
function finishRoute(dest){closeOnboarding();if(dest==="home")return document.querySelector('.nav-btn[data-page="home"]')?.click();if(dest==="smart")return document.dispatchEvent(new CustomEvent("levelup:navigate",{detail:{page:"program-builder"}}));document.querySelector('.nav-btn[data-page="workout"]')?.click();setTimeout(()=>{if(dest==="templates")document.querySelector("[data-template-build]")?.click()},80)}
function selectedExercises(){const map=new Map(getAllExercises().map(x=>[x.id,x]));return answers.excludedIds.length?answers.excludedIds.map(id=>`<button class="onboarding-selected-exercise" type="button" data-avoid-remove="${esc(id)}">${esc(map.get(id)?.name||id)} ×</button>`).join(""):'<small class="onboarding-helper">No exercises selected.</small>'}
function renderExerciseResults(){const host=overlay?.querySelector("#onboarding-exercise-results");if(!host)return;const q=String(answers.exerciseSearch||"").trim().toLowerCase(),selected=new Set(answers.excludedIds),results=getAllExercises().filter(x=>x.trackingType!=="notes"&&!selected.has(x.id)).filter(x=>!q||[x.name,x.muscleGroup,x.equipment].some(v=>String(v||"").toLowerCase().includes(q))).sort((a,b)=>String(a.muscleGroup).localeCompare(String(b.muscleGroup))||String(a.name).localeCompare(String(b.name))).slice(0,12);host.innerHTML=results.length?results.map(x=>`<button class="onboarding-exercise-row" type="button" data-avoid-add="${esc(x.id)}"><span><strong>${esc(x.name)}</strong><small>${esc(x.muscleGroup)} · ${esc(x.equipment)}</small></span><b>Avoid</b></button>`).join(""):'<p class="onboarding-helper">No matching exercises.</p>'}
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
document.addEventListener("levelup:open-profile-setup",()=>openOnboarding({manual:true}));
initializeAcquisitionTracking();
initializeFirstRunOnboarding();
